### ISSUE TITLE
Formally deprecate readtable

### ISSUE THREAD

**Issue by randyzwitch** [JuliaData/DataFrames.jl#1240]
I just got caught in an upgrade to DataFrames master where `readtable` just becomes undefined, where it works in DataFrames 0.10.1. 

Per the issue below, it appears that it's moving to CSV.jl, but it feels like a deprecation warning is needed, I have to imagine this function was used quite a bit.

https://github.com/JuliaData/DataFrames.jl/issues/1133

Example, works on 0.10.1:

```julia
julia> using DataFrames, HTTP
julia> f = HTTP.get("http://goo.gl/UDv12g")
julia> satData = readtable(f.body)
```
Doesn't work on master

```julia
julia> satData = readtable(f.body)
ERROR: UndefVarError: readtable not defined
```

**Comment by nalimilan** [comment]
The problem is that CSV depends on DataFrames (since it uses it as its default table type), so DataFrames cannot depend on CSV. We need to first tag a release of the Nulls-base DataFrames which doesn't depend on CSV, then we will be able to tag a version of the Nulls-base CSV which depends on (the Nulls-base) DataFrames, and finally we will be able to tag a release of DataFrames which depends on CSV. We could do that in the same day so that users do not notice.

**Comment by randyzwitch** [comment]
Ok, just bringing it up here in case it was unexpected. But it sounds like there's a plan, so no problem :)

**Comment by nalimilan** [comment]
See https://github.com/JuliaData/DataFrames.jl/issues/1240.
