### ISSUE TITLE
Join on columns of different name

### ISSUE THREAD

**Issue by cjprybol** [JuliaData/DataFrames.jl#1297]
Transfer of https://github.com/JuliaData/DataTables.jl/issues/78

idea summary: Use a 2-element tuple to support joining DataFrames on columns that do not have the same names. Currently, we require renaming columns so that they match before columns can be used for joining

```julia
join(a, b, on=(:a_name, :b_name))
join(a, b, on=[(:a_name1, :b_name1), (:a_name2, :b_name2)])
```

[Pandas does this more explicitly by having `left_on` `right_on` keywords](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html#pandas-dataframe-merge), and R's Data.Table has `by.x` and `by.y` ([jump to page 61 in docs](https://cran.r-project.org/web/packages/data.table/data.table.pdf))

**Comment by ararslan** [comment]
I'd suggest using pairs, e.g. `join(a, b, on=[:a_name1 => :b_name1, :a_name2 => :b_name2])`

**Comment by nalimilan** [comment]
I'm hesitant about using `Pair`. That kind of suggests a direction or a movement, but here the two column names are treated symmetrically. I would make sense if the second column name was retained in the result, but using the first one would sound more natural (that's what R does at least). OTOH, pairs make it clearer that matching columns need to be grouped, rather than grouping by (left, right). Without them it's really hard to remember.

Anyway, if we use `first` and `last` internally, we can support both tuples and pairs, so we just need to choose which syntax we promote in the docs.

**Comment by cjprybol** [comment]
closed via https://github.com/JuliaData/DataFrames.jl/pull/1312
