### ISSUE TITLE
Possible improvement of hcat

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1301]
Consider the following code:
```
 x = DataFrame([(i,j) for i in 1:3, j in 1:4])
hcat(x, [1,2,3])
```
works OK, but:
```
hcat([1,2,3], x)
```
fails.

Additionally:
```
hcat([1 2 3], x)
```
appends `DataFrame` to `[1 2 3]` in fourth position.

Is this intended, or should it be fixed.

**Comment by bkamins** [comment]
Also this is probably something we should avoid (`x` is a DataFrame):
```
hcat(x, "bad mistake")
```
which produces StackOverflow.

**Comment by nalimilan** [comment]
I don't think that's really intended, but it's difficult to fix in full generality since AFAIK there's no way to define a method which is called when at least one of the arguments is a `DataFrame`. See https://github.com/JuliaLang/julia/pull/20815. I guess we could add methods to handle the two-argument case at least, since it's likely to be the most common one. PR welcome.

Regarding the stack overflow, it seems it could be fixed by adding a two-argument `hcat!` method to stop the recursive call of `hcat!(a::DataFrame, b, c...)`.

**Comment by bkamins** [comment]
This is what I meant. I will make a PR (I was not so much into DataFrames development earlier so I do not know well what already has been considered and decided).

**Comment by bkamins** [comment]
closing as the PR is merged.
