### ISSUE TITLE
sub df by row or column

### ISSUE THREAD

**Issue by Wikunia** [JuliaData/DataFrames.jl#1313]
I know dataframes is more column focused...
If I have a dataframe `df`
and then use

```
df[[1,2,3],:]
```
it return the first three rows.

If I do:

```
df[[1,2,3]]
```
I get the first three columns. This is a bit confusing to me.
If it is more column focused shouldn't it be 

```
df[:,[1,2,3]]
```
in the first place? I know that would be breaking.

The other variant would be:

```
df[[1,2,3]]
```
get the first three rows and

```
df[[:bla,:blub,:last]]
```
might return those columns. If I mention an integer it is most of the time the row and not the column which can be retrieved by name.

**Comment by ararslan** [comment]
The problem here is that using a single index into a `DataFrame` retrieves columns by index rather than rows, which several folks in https://github.com/JuliaData/DataFrames.jl/issues/1200 have noted is rather odd. I'm going to close this and further discussion can happen in #1200 should there be anything else to add. Thanks!
