### ISSUE TITLE
Pkg.update keeps at 0.10.1

### ISSUE THREAD

**Issue by davidbp** [JuliaData/DataFrames.jl#1355]
Hello,

When I try to update to the version 0.11 I get the followig message:

```
julia> Pkg.update("DataFrames")
INFO: Updating METADATA...
INFO: Computing changes...
INFO: Package DataFrames was set to version 0.10.1, but a higher version 0.11.5 exists.
      To install the latest version, you could try updating these packages as well: CSV and MLDataUtils.
INFO: No packages to install, update or remove
```

Even if I try to update CSV and MLDataUtils I still get the message.

I am testing this in the following machine:

```
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

Is there an easy solution to this problem?

**Comment by nalimilan** [comment]
You probably have some installed packages that depend on DataFrames 0.10.1. The easiest solution to find out which one is to remove (temporarily) packages that depend on DataFrames, DataTables, CSV or DataStreams. See https://discourse.julialang.org/t/how-to-upgrade-from-dataframes-0-10-1-to-0-11-3/8243/. Feel free to ask for help on Discourse, I'm closing this issue since we reserve GitHub for bug reports.

**Comment by davidbp** [comment]
If someone has the same problem the function written here:

https://discourse.julialang.org/t/how-to-find-package-preventing-others-from-updating/8235

Was super usefull to find the dependencies that prevented the package to be installed.
