### ISSUE TITLE
Scalar indexing by row should return a DataFrameRow

### ISSUE THREAD

**Issue by rofinn** [JuliaData/DataFrames.jl#1400]
Example)
```julia
julia> df
10×3 DataFrames.DataFrame
│ Row │ A  │ B         │ C     │
├─────┼────┼───────────┼───────┤
│ 1   │ 1  │ 0.778923  │ true  │
│ 2   │ 2  │ 0.292706  │ false │
│ 3   │ 3  │ 0.8056    │ true  │
│ 4   │ 4  │ 0.868616  │ false │
│ 5   │ 5  │ 0.788371  │ false │
│ 6   │ 6  │ 0.0806976 │ true  │
│ 7   │ 7  │ 0.909549  │ true  │
│ 8   │ 8  │ 0.609525  │ true  │
│ 9   │ 9  │ 0.0454008 │ true  │
│ 10  │ 10 │ 0.214475  │ false │

julia> obs = df[1, :]
DataFrameRow (row 1)
A  1
B  0.7789232193182367
C  true

julia> obs[:A]
1
```

NOTE: Unfortunately, this breaks a lot of existing functionality (e.g., `DataFrameRow`s depend on the existing `df[1, :]` behaviour), so this may result in a larger discussion around replacing DataFrameRows with a `Dict` or `NamedTuple`. Similarly, we may want to move in the direction where a `DataFrame`s is just an alias for a `Dict{Symbol, <:AbstractVector}` or `NamedTuple`.

**Comment by nalimilan** [comment]
+1

Regarding the fact that `df[1, :]` fails, it shouldn't be hard to fix since the code for `getindex` already exists, it just needs to be moved from `DataFrame` to `DataFrameRow` methods.

We've discussed replacing `DataFrameRow` with `NamedTuple` before at https://github.com/JuliaData/DataFrames.jl/issues/1337, but unfortunately it's not really possible since you couldn't do things like `row[:x] += 1`. So we should probably keep `DataFrameRow`, but have it behave like a `NamedTuple` as much as possible, in particular via field overloading. Also a `Dict` would really be too slow and that's not the right structure for this (the parent data frame already includes a dict to lookup columns).

**Comment by ararslan** [comment]
If we express a `DataFrame` as something like
```julia
const DataFrame = NamedTuple{names,<:NTuple{N,<:AbstractVector}} where {names,N}
```
then we would get mutable rows trivially, since to get a row you'd need to get a column first, which would expose the underlying vector. However, indexing then becomes much less convenient...

**Comment by nalimilan** [comment]
Yeah, but that would amount to fixing the problem by removing the feature... :-/

**Comment by ararslan** [comment]
What's the problem? :trollface:

**Comment by pdeffebach** [comment]
I'm bumping this, and also gonna say that we should overload vector operations on a dataframe row (or even make it `<: AbstractVector`!) so that we can do stuff like this naturally
```
vars = [:x1, :x2, :x3]
for row in eachrow(df)
   row[:mean_var] = mean(df[:vars])
end
```

**Comment by nalimilan** [comment]
Want to work on it? :-p

**Comment by pdeffebach** [comment]
Yeah. I'll take a stab at this!

**Comment by pdeffebach** [comment]
Stackoverflow everywhere! It turns out `DataFrameRow` just calls `df[1,:]` everywhere. Is it bad programming practice to add a helper function that behave like `getindex` and use that everwhere in `dataframerow.jl`?

**Comment by pdeffebach** [comment]
I also am more pro `DataFrameRow`-as-vector. `dfr[1]` returns a `Float` but upon iteration, it returns tuples, is very weird. But I don't quite understand enough about the reasons for doing this as such.

**Comment by nalimilan** [comment]
> Stackoverflow everywhere! It turns out DataFrameRow just calls df[1,:] everywhere. Is it bad programming practice to add a helper function that behave like getindex and use that everwhere in dataframerow.jl?

I guess this means the relationship between `DataFrame` and `DataFrameRow` should be reversed. If `getindex` for `DataFrame` returns a `DataFrameRow`, `DataFrame` has to be aware of the existence of `DataFrameRow` and implement its `getindex` method for it.

> I also am more pro DataFrameRow-as-vector. dfr[1] returns a Float  but upon iteration, it returns tuples, is very weird. But I don't quite  understand enough about the reasons for doing this as such.

Yes, I think we should change that so that `DataFrameRow` behaves like `NamedTuple` and `Vector`. See https://github.com/JuliaData/DataFrames.jl/pull/1439#discussion_r201210397.

However, after thinking a bit more about this, I wonder whether we should change `getindex`. Making the comparison with matrices, indexing a row returns a copy, and if you want in-place modification you need to do `x[i, :] .+= 1` or use `view`. Among other things, returning a `DataFrameRow` would mean that if you store it somewhere and mutate the data frame, the value will change, which may be unintended. Returning a `NamedTuple` from `getindex`, but a `DataFrameRow` from `view` would be more consistent with matrices. Maybe there are reasons to have `DataFrame` work differently, but if so we should be clear about them.

Regarding the use case of iterating over rows to mutate them at https://github.com/JuliaData/DataFrames.jl/issues/1400#issuecomment-403796933, it can still work since `eachrow` yields `DataFrameRow` objects. What's needed rather is to change `DataFrameRow` as noted above so that it behaves like tuples and vectors and that `mean(row[vars])` works.

So my current proposal: change `getindex` to return `NamedTuple` (and require Julia 0.7 for that), change `DataFrameRow` to behave like `NamedTuple` (but mutable).

**Comment by davidanthoff** [comment]
I like the idea, but it is also massively breaking. How would the deprecation story look like?

I also think it would be good if the basic API for DataFrames.jl would rather sooner than later be just set in stone. We just had the massive breaking change with Missing which was unbelievable disruptive, and this also seems quite impact full. There is _so_ much code out there that relies on DataFrames.jl that I think it really shouldn't break things every half year or so...

**Comment by nalimilan** [comment]
> I like the idea, but it is also massively breaking. How would the deprecation story look like?

Can you illustrate where it would be breaking? Do you depend on this a lot?

Breaking changes are annoying, but DataFrames is an old package and it doesn't always reflect the way recent Julia versions work. Using `NamedTuples` seems obvious now that they exist in 0.7. Before do that before 1.0 as much as we can.

**Comment by davidanthoff** [comment]
It doesn't really bother me personally, but I have a group of ~10 folks that use julia for their scientific work (not as contributors to packages), and these kinds of changes drive them nuts, and I think if it wasn't that I keep them on julia, they would probably long have moved off to other platforms because of that. I just generally think that the churn in key packages like DataFrames is almost the biggest obstacle for more widespread adoption (at least based on the conversations I have with folks).

I do see the need to update things, but maybe we could at least try to have one more breaking release, and bunch breaking things together in one release, and then call it a day? These kind of staggered breaking releases are really much more painful for normal users.

**Comment by nalimilan** [comment]
OK. Honestly, I'm not sure this change would be really disruptive in practice. It's not that common to index a single row AFAICT, in particular because it currently allocates a new data frame, which is really inefficient and not very useful.

In regard to bundling several breaking things in one release, I don't think there are many breaking changes planned in the short term. Generally speaking I agree it makes sense to adopt a clearer release schedule after Julia 1.0 is released. But I'm afraid the API still carries a lot of legacy which isn't very Julian nor consistent (e.g. https://github.com/JuliaData/DataFrames.jl/issues/1200). Hopefully we can introduce a new API without breaking existing ones in stable releases.

**Comment by pdeffebach** [comment]
>  Returning a NamedTuple from getindex, but a DataFrameRow from view would be more consistent with matrices. Maybe there are reasons to have DataFrame work differently, but if so we should be clear about them.

I'm not sure how useful this is because I think the majority of uses of `DataFrameRow` are to modify the dataframe its attached to. This change would make `eachrow(df)` an awkward tool if it were to still iterate `DataFrameRows`

**Comment by nalimilan** [comment]
https://github.com/JuliaData/DataFrames.jl/pull/1449 introduces a deprecation (on Julia 0.7, where `pairs` exists), to ensure a smooth transition if anybody relies on the current behavior of `DataFrameRow`.

**Comment by nalimilan** [comment]
> I'm not sure how useful this is because I think the majority of uses of DataFrameRow are to modify the dataframe its attached to. This change would make eachrow(df) an awkward tool if it were to still iterate DataFrameRows
> 
> I think that if df[:a] = x modifies df, then df[1,:] = y should modify df

`df[1, :] = 1` calls `setindex!`, so it could still modify entries. (BTW, for arrays now `x[1, :] = 1` is deprecated in favor of `x[1, :] .= 1`, which calls `broadcast!(identity, dotview(x, 1, :), 1)`. We could take the same approach, which would be consistent with our `view`.)

Also I don't see why it would be weird to keep `eachrow` returning `DataFrameRow` objects. It would behave almost the same as direct indexing, except that it would allow mutation. It's quite unlikely that one would like to store a row from this kind of loop, so it's fine if it reflects changes in the parent data frame (contrary to indexing).

**Comment by pdeffebach** [comment]
Sounds good. I misunderstood earlier. 

as long as I can do 

```
df[:a] .= 0
for row in eachrow(df)
   row[:a] = mean(row[:vars])
end
```

Then I'm happy. 

One thing to note is that DataFramesMeta's `@byrow!` implementation doesn't use `eachrow`. Maybe a PR to use `eachrow` that it's more efficient could be good.
