### ISSUE TITLE
Describe throws an error on 0-row DataFrame.

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1467]
As in the heading. Running `describe` on 0-row `DataFrame` throws an error. We probably should handle this as a special case.

CC @pdeffebach 😄.

**Comment by pdeffebach** [comment]
Working on this!

The error is super weird. cause everything seems to be in a `try... catch` block. I am thinking of just setting `stats` to be `eltype` and `nmissing`, so they at least know the types of all their empty columns. Then print a helpful message (warning message?) telling them we may have changed the behavior they expected because their dataframe is empty.

**Comment by pdeffebach** [comment]
Actually, should we do this?

Whoever wrote `mean` probably thought about what happens with an array of length zero and decided this was the way to go. We don't want to override default behavior.

**Comment by bkamins** [comment]
I guess whoever wrote `mean` was defining this when data-science related features were not in Base julia. `mean` on empty collection throws an error, but it returns `NaN` when the collection is an array - probably for type-stability reasons (but it could throw an error equally well I guess).

Anyway - we can leave the current behavior for now (although it is a bit confusing IMHO).

**Comment by pdeffebach** [comment]
Sounds good. 

I will work on putting `ifs` everywhere and then tackle #1443 for porting `describe` to a grouped dataframe.

**Comment by pdeffebach** [comment]
Added the tests in #1488  so we can close this.
