### ISSUE TITLE
Show of categorical values in a DataFrame

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1496]
Consider a following example:

```
julia> df = DataFrame(A = categorical([1,2]), B=categorical(1.0:2.0), C=categorical(["a","b"]))
2×3 DataFrame
│ Row │ A                                │ B                                    │ C │
├─────┼──────────────────────────────────┼──────────────────────────────────────┼───┤
│ 1   │ CategoricalValue{Int64,UInt32} 1 │ CategoricalValue{Float64,UInt32} 1.0 │ a │
│ 2   │ CategoricalValue{Int64,UInt32} 2 │ CategoricalValue{Float64,UInt32} 2.0 │ b │
```

We have two issues here:
1. Inconsistency in showing `CategoricalString` and `CategoricalValue`
2. `CategoricalValue` is displayed very verbosely.

I think it would be better to:
1. omit printing type information for `CategoricalValue`
2. add some visual indication that a column is `CategoricalValue` or `CategoricalString`; two ideas are: using a different color to print column name or putting some mark (a star?) in front of column name instead of a space, so it would look like this:

```
julia> df = DataFrame(A = categorical([1,2]), B=categorical(1.0:2.0), C=categorical(["a","b"]))
2×3 DataFrame
│ Row │*A │*B   │*C │
├─────┼───┼─────┼───┤
│ 1   │ 1 │ 1.0 │ a │
│ 2   │ 2 │ 2.0 │ b │
```

**Comment by nalimilan** [comment]
Yes, I think there's a more general problem here. In Julia 0.6, the `compact` property allowed opting for a more compact printing, but in 0.7/1.0 one also needs to set `typeinfo`. The problem is, we don't print the element type of columns, so passing `:typeinfo => eltype(col)` would be a slight abuse (not the end of the world, though).

I do think it would make sense to print some indication of the type in the header. dplyr's tibbles do that in R, and types are even more important in Julia. Among basic types `Int` is relatively short, `Float64` is also OK given that there will most likely be decimals, and `String` is reasonable too. But other types will generally be too long, `CategoricalValue`/`CategoricalString` being a case in point (even without type parameters). So maybe we need to compute abbreviations, possibly with a standardized list for common types, e.g. `Categorical`.

**Comment by bkamins** [comment]
Or maybe have special cases for `CatValue` and `CatString` and allow up to 9 characters?

**Comment by nalimilan** [comment]
Maybe cut at 9 characters or before the first uppercase letter or digit, whichever comes first? In addition to that, we can always add a special case for categorical values if we want to distinguish `CategoricalValue` from `CategoricalString` (but is that really needed?).

**Comment by bkamins** [comment]
so maybe something like:
```
compacttype(T::Type) = match(r"^.{1,4}[a-z_]{0,5}", string(T))
```
to guarantee at least 4 characters whatever they are, no more than 9 but after 4th character only lowercase letters and underscore are accepted? (this is designed in particular to catch strip parametric types like `Union` properly or `Vector`)

**Comment by nalimilan** [comment]
Looks nice, but we should also treat a sequence of digits as a word, i.e. never cut it in the middle. Currently `Int64` gives `Int6`. It should also be fine to allow them beyond 4 characters as long (as the sequence doesn't go beyond 9).

Finally, to avoid confusion, we could add an ellipsis when the name is abbreviated.

**Comment by nalimilan** [comment]
Looks good. I'm not sure about `?` since its attribution hasn't been decided yet, but that's a detail. We could also use `⯑` in the meantime.
