### ISSUE TITLE
Internal design issue with `columns` function

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1545]
We currently have `Tables.columns` function and internal `columns` function defined (the latter returns `Cols` object), which is heavily used internally. Is there any opinion what we should do with it (I did not design it but I least I would try to avoid name clash).

**Comment by nalimilan** [comment]
Good question. There's a definition `Tables.columns(df::AbstractDataFrame) = df` in Tables.jl, which makes that function not very useful for DataFrames. But since that function isn't exported either, that doesn't sound a big problem.

I'm tempted to export something like `columns` from DataFrames to allow things like `mean.(columns(df))` to compute column-wise means, mostly replacing `eachcol`. But the implementation could be different from the existing (purely internal) one.

Cc: @quinnj

**Comment by quinnj** [comment]
`Tables.columns` is intentionally not exported and will never be; so there shouldn't be any concern with potentially clashing, though it might be confusing for users. I don't have a strong opinion here; being able to do `mean.(columns(df))` does sound appealing.

**Comment by nalimilan** [comment]
OK, so we can keep it that way for now, and export it later if we want.

**Comment by bkamins** [comment]
Closing as we now have `eachcol` implemented that does all that is needed and after deprecation period it will be consistent with Julia 1.1.
