### ISSUE TITLE
Support for column selection in views

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1557]
`SubDataFrame` and `DataFrameRow` should have an internal field allowing them to store information that they operate on a subset of columns.

From https://github.com/JuliaData/DataFrames.jl/pull/1534#discussion_r221465110.

**Comment by bkamins** [comment]
Assume you have a `DataFrame` with coulmns `:a`, `:b`, and `:c`.

We create its view `sdf1 = view(df, 1, [:a, :b])`.

Now remove column column `:a` from the `DataFrame` entirely; what should be the result of `sdf1[1]` - it is clear for me that this is problematic and whatever we do we will not find a consistent rule.

Therefore my conclusion is that we should:
* clearly state that `view` does not guarantee anything if the source `DataFrame` is mutated in any way (except changing values in columns, but not: adding/deleting/renaming columns nor adding/removing/reordering rows)
* we can store two variables in `SubDataFrame` and `DataFrameRow` constructor:
    * `parent` (a pointer to a `DataFrame` that was passed to `view`)
    * `source` (a `DataFrame` actually used for column look-up) - it would be equal to `parent` if all columns are selected.

This `parent`/`source` distinction would create no performance overhead. The only benefit is that `parent(sdf)` would always return a `DataFrame` that was used to create a view. I am not sure if this is important to have, but if it is we could have such an implementation. If this is not something useful, then we can stay with the current implementation and simply accept that `parent` sometimes points at data frame passed to `view` and sometimes to some other data frame.

**Comment by nalimilan** [comment]
I was thinking we could rather add a field indicating the subset of columns which are retained. That shouldn't incur any performance overhead either if it was an `Index` object, so that we resolve names to integer indices directly, to avoid doing the lookup twice.

I agree that we cannot guarantee that the view will still work after mutating the parent. We should just ensure we print reasonable errors and not crash nor return unexpected results. In particular, we need to do something logical if columns are renamed or reordered; the problem being that they can be specified either by names or by position, which would require different behaviors (i.e. follow names if names were provided, follow order if integer indices were provided).

**Comment by bkamins** [comment]
I have considered this, but:
1. as you say - we would have to have dual logic depending on what was used to create a view;
2. it would introduce a performance overhead on each `getindex` to `SubDataFrame`/`DataFrameRow`, when creating a `source` `DataFrame` we pay this overhead only on construction.

**Comment by nalimilan** [comment]
The trade-off is different for `SubDataFrame` and `DataFrameRow`. For the latter, construction must absolutely be cheap. The only way to ensure that, assuming e.g. a pattern where the user would loop over rows of a data frame and call `view(df, row, cols)`, would be to have `DataFrameRow` store `cols` in a field without copying it. Then since it's an immutable `struct` the compiler should be able to elide actually creating the object. But that would require storing indices as provided (i.e. names, integers or Boolean). Or maybe we'd better not support that operation at all if it's doomed to be so inefficient.

**Comment by bkamins** [comment]
Yes, but - as I said - you would have to pay the same cost for `DataFrameRow` when you wanted to do anything with it. It would be cheap to create but expensive to use (in general the problem is that in order to properly select a column you have to more or less do the same what `df[cols]` does - the only difference would be that this would be a lazy operation on read) - and I guess most users would want to do something with this `DataFrameRow`.

My current thinking is to leave the implementation as is and directly hint to users that `view(df, row, cols)` is much faster when `cols` is a colon and it is advised to do `view(df[cols], row, :)` rather than `view(df, row, cols)` if performance is important (and we can do this in all standard library code - actually this is how it works now).

We should support `view(df, row, cols)` for consistency reasons though.

But if you see the way to solve the problem of *performance of lazy evaluation of `cols` against parent `df` columns* I am open 😄.

**Comment by bkamins** [comment]
Closing, as currently I do not see a better solution than we have in #1603. `DataFrameRow` in order to be fast needs to take all columns of a source data frame.
