### ISSUE TITLE
Future of colwise

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1595]
Following https://github.com/JuliaData/DataFrames.jl/pull/1590#discussion_r232497822 I would like to discuss here what we should do with `colwise` function.

Now its basic form `colwise(f, df)` is the same as `map(f, columns(df))`, but we have also two additional methods:
* one producing a matrix when multiple functions are passed as `f` argument (works only for a data frame);
* one producing an array of arrays when a single function is applied to a grouped data frame.

How useful do you think those are and is is worth to keep `colwise` defined or should we deprecate it.

**Comment by nalimilan** [comment]
I'm not sure these two methods are very useful. Since they return arrays, they don't include any information about the names of applied functions or about the groups. Anyway this behavior is easy to get using array comprehensions.

Typically, when applying a function on each group, you want the grouping column to be able to interpret the result, so you'd use `map(df -> map(f, columns(df)), gd)`, or `map(gd) do f.(columns(df)) end`. It could be useful to provide a convenience function to do that, maybe via `map(f, columns(gd))` and `f.(columns(gd))`? The similarity with the `DataFrame` syntax is appealing.

**Comment by bkamins** [comment]
I would deprecate `colwise` then. OK?

Users can use `map` or `mapcols`. I guess in the long run when @nalimilan redesigns `GroupedDataFrame` API some additional convenience methods for this type can be implemented.

**Comment by nalimilan** [comment]
Yes, let's deprecate it!
