### ISSUE TITLE
`by` with arrays of inputs and broadcasting

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#1615]
It looks like the splatting doesn't quite work with having vectors of columns you want to act on. 

```
using Statistics
df = DataFrame(x = repeat(1:2, 5), a=rand(10), b=rand(10));
by(df, :x, [:a, :b] .=> mean, :b => std) # doesn't work
#=
ERROR: MethodError: no method matching by(::DataFrame, ::Symbol, ::Array{Pair{Symbol,typeof(mean)},1}, ::Pair{Symbol,typeof(std)})
=#
by(df, :x, :a => mean, :b => std) # works
```

I'm done with grad apps now so I will see if I can poke around for a fix soon.

**Comment by bkamins** [comment]
I thought that this was intentional, but we can add merging as @nalimilan writes. The rules would be to merge:
* with positional arguments:
    * `Pair`s and `Tuple`s of `Pair`s into a single `Tuple` (this is pretty clear that it should be allowed and is simple)
    * several `NamedTuple`s of `Pair`s into a single `NamedTuple` (this is pretty clear that it should be allowed and is simple)
* with keyword arguments: here it is problematic as we would have to allow mixing positional and keyword arguments (this will be more involved to get it fully right as there are many possible problematic combinations to safeguard against) - @pdeffebach is there a need to handle this case?

**Comment by pdeffebach** [comment]
I agree that named-tuple for broadcasted arguments is not necessary. But I think that this should be allowed. 

Yes I think merging should do the trick, we can discuss more in depth once I make a PR/

**Comment by bkamins** [comment]
@pdeffebach When you write a PR please take this behavior into account:
```
julia> merge((a=1, b=2), (b=10, c=20))
(a = 1, b = 10, c = 20)
```
so duplicates are silently overwritten. We do not want this I think and an error should be thrown in case of a duplicate.

**Comment by bkamins** [comment]
This is done, so I am closing this. We are missing `All`, `Not` and `Between` broadcasting, but this is a separate issue (the mechanics is there). If you feel something needs to ba added here please reopen.
