### ISSUE TITLE
TableTraits v0.4.1 breaks `DataFrame` constructor

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1649]
After v0.4.1 release of TableTraits.jl DataFrames.jl is broken:
```
julia> DataFrame(Any[1:3, 1.0:3.0, ["a","b","c"]])
ERROR: type StepRangeLen has no field start
```
(this worked in the past)

CC @nalimilan, @davidanthoff

**Comment by bkamins** [comment]
@nalimilan what do you think we should do:
1. keep the functionality from TableTraits.jl breaking DataFrames.jl
2. add a work-around in DataFrames.jl to allow `Vector{Any}` as in the past.
3. some other option (e.g. pin TableTraits.jl to version 0.4.0)

**Comment by nalimilan** [comment]
We should at the very least add a deprecation to allow people to adjust their code without immediate breakage. A few possibilities for the long-term behavior:
- require using `Vector{AbstractVector}`
- require providing names via the second argument to indicate the first argument should be interpreted as a list of column vectors
- add code in the constructor to check whether all entries in the vector are vectors, and if so avoid calling the TableTraits method

The last solution could be ideal if it's not too complex or hacky.

**Comment by bkamins** [comment]
I do not use TableTraits.jl so I do not know its use cases well.
Do you feel in place to make a decision (I am largely indifferent as long as we do not have tests failing)?

**Comment by nalimilan** [comment]
I don't think any of my proposals conflicts with TableTraits uses. AFAIK it needs entries (rows) to be named tuples, so we can do whatever we want in other cases. That's more of a question regarding the DataFrames API, and (for the last one) whether it works in practice (need to look at the code).

**Comment by bkamins** [comment]
The problematic method is `DataFrame(x)` catch all method that was recently added to `other/tables.jl`.

**Comment by davidanthoff** [comment]
Arggh, I'm sorry, I had a vague feeling that this might cause trouble somewhere...

But the change in [TableTraits.jl](https://github.com/queryverse/TableTraits.jl) was essentially a bug-fix that I think exposed an issue now here in the constructor for ``DataFrame``.

The previous version of ``isiterabletable`` returned ``false`` for a ``Vector{Any}``, but that of course is incorrect, because say ``Any[(a=1,b=2), (a=3,b=40]`` is a valid table. So now the new version returns ``missing`` in the case of ``Vector{Any}``, meaning one can't tell based on the type itself whether something is a table or not. That seems, semantically, the correct behavior here.

I think essentially the code in [this](https://github.com/JuliaData/DataFrames.jl/blob/aa6968c6058025868176eda6c02695ae76d0c763/src/other/tables.jl#L28) branch right now is incorrect: ``TableTraits.isiterabletable`` tells the code there that it can't tell whether ``x`` is an iterable of ``NamedTuples``, and then that branch just continues assuming it is. But, it could actually be a vector of vectors...

I think @nalimilan last solution (essentially moving [this](https://github.com/JuliaData/DataFrames.jl/blob/aa6968c6058025868176eda6c02695ae76d0c763/src/other/tables.jl#L33) branch somewhat up in the constructor) would work for now, but I think we'll still be left with some weird corner cases...

The question then is what to do with an iterator that returns ``HasEltype()`` and ``eltype(x)===Any`` for example... I had a solution for that situation for the pure [TableTraits.jl](https://github.com/queryverse/TableTraits.jl) world, but I'm less sure how that could/would be handled now that [Tables.jl](https://github.com/queryverse/TableTraits.jl) is involved (I have to admit that at this point things have become so complex that I no longer fully understand what code is running when etc...).

As a short term fix, there seem to be two options:
1. I could undo the TableTraits.jl change for now. It is not super urgent, and if it caused a great deal of trouble that would be an option.
2. We go with @nalimilan's suggestion.

I would prefer 2), given that that seems more correct, but if that is tricky for one or another reason we can also run with 1) for now.

**Comment by davidanthoff** [comment]
Yeah, I think that would work!

**Comment by nalimilan** [comment]
OK, let's try that: https://github.com/JuliaData/DataFrames.jl/pull/1650.
