### ISSUE TITLE
Building DataFrames.jl on windows requires admin privileges

### ISSUE THREAD

**Issue by felipenoris** [JuliaData/DataFrames.jl#1754]
This happens due to CodecZlib.jl .

See https://github.com/bicycle1885/CodecZlib.jl/issues/43 .

**Comment by bkamins** [comment]
@nalimilan - I have wanted to remove `readtable` and `writetable` form the package sources for some time now. This is yet another argument for it (and it should make DataFrames.jl have lighter dependencies in general + load a bit faster on startup).

**Comment by nalimilan** [comment]
We could drop `readtable`, but it sounds quite easy to drop the additional dependencies, so... See https://github.com/JuliaData/DataFrames.jl/pull/1755.

**Comment by davidanthoff** [comment]
Shouldn't this just be fixed in BinaryProvider? There seems to be an issue already: https://github.com/JuliaPackaging/BinaryProvider.jl/issues/149.

**Comment by bkamins** [comment]
Yes - this is a long known issue. I simply think that we do not need these dependencies in DataFrames.jl anyway (in general my view is that DataFrames.jl should be 100% Julia including all its dependencies).

**Comment by bkamins** [comment]
Just to expand on for possible future readers of this thread:

> DataFrames.jl should be 100% Julia including all its dependencies

We want to be sure that when DataFrames.jl fails badly (e.g. core dumps) this must mean only one of the following two reasons:
* there is a bug in Base
* an unsafe operation in-built into the language (like `@inbounds`) was used

so that the user can exclude the possible cause that e.g. some third-party C code used by DataFrames.jl has a bug.
This is in practice very relevant as columns of `DataFrame` can have a myriad of sources. People often report that DataFrames.jl fails. As of now - when we exclude the two points above by doing code analysis of DataFrames.jl functions only we can safely say that the bug is not in DataFrames.jl.
