### ISSUE TITLE
Inconvenient use of iterate in fallback DataFrame constructor

### ISSUE THREAD

**Issue by quinnj** [JuliaData/DataFrames.jl#1785]
On [this line](https://github.com/JuliaData/DataFrames.jl/blob/master/src/other/tables.jl#L24), we call `all` on any iterable input, which starts iterating the source. This is unfortunate when iterating is expensive for the source, as is currently the case for an SQLite.Query. I'm brainstorming ways to work-around this (and not make iterating an SQLite.Query so stateful), but the sqlite interface is very limited in this regard. I also ran into another case where the source was iterable, yet empty, and then got caught in this branch, but then errored on the core DataFrames constructor because the empty column names comprehension produced a `Union{}[]`.

**Comment by bkamins** [comment]
Yes - this kind of thing occurred when trying to convert JuliaDB table without column names if I remember correctly.

In general in line https://github.com/JuliaData/DataFrames.jl/blob/master/src/other/tables.jl#L25 we iterate over `x` anyway so we might produce a vectors of column values and names first and then check what they are.

Also maybe (but I am not an expert in the design here) we could move https://github.com/JuliaData/DataFrames.jl/blob/master/src/other/tables.jl#L29 before https://github.com/JuliaData/DataFrames.jl/blob/master/src/other/tables.jl#L23 so that if something follows Tables.jl interface it gets handled by `Tables.columns` which can be made efficient wrt the source?

**Comment by bkamins** [comment]
Is this also fixed by #1789?

**Comment by nalimilan** [comment]
@quinnj Can you confirm?

**Comment by quinnj** [comment]
Yep!
