### ISSUE TITLE
Omitted columns when displayed in Jupyter notebook

### ISSUE THREAD

**Issue by tk3369** [JuliaData/DataFrames.jl#1794]
Hi.

I would like to report a usability issue with this new version (0.18.1).  

When the data frame is shown in jupyter notebook, it is cutting off the columns as if it's in a console screen.  I used to be able to scroll horizontally to see data from all columns.  Is there any way to get that function back by default?  Thanks.

**Comment by bkamins** [comment]
Before you start Jupyter Notebook with `notebook` method write `ENV["COLUMNS"] = 1000` (or any other large number you like).

Here is an example session:

```
julia> ENV["COLUMNS"]
"1000"

julia> using IJulia

julia> notebook(dir=pwd())
```

[Here](https://github.com/JuliaData/DataFrames.jl/pull/1761#issuecomment-484108293) are some other options mentioned by @stevengj when we changed this functionality. In particular you can modify `ENV["COLUMNS"]` in kernel configuration file so that you do not have to remember changing it every time you start a new notebook. Here is an example of my current kernel configuration:
```
{
  "display_name": "Julia 1.1.0",
  "argv": [
    "path_to_julia",
    "-i",
    "--startup-file=yes",
    "--color=yes",
    "--project=@.",
    "path_to_ijula_kernel.jl",
    "{connection_file}"
  ],
  "language": "julia",
  "env": {
    "COLUMNS": "1000",
    "LINES": "100"
  },
  "interrupt_mode": "message"
}
```

I will add a documentation for this.

However, if you would find that we should change it please comment what would be the recommended approach.

**Comment by bkamins** [comment]
See #1795

**Comment by tk3369** [comment]
Thanks for the link and workaround.
