### ISSUE TITLE
Use semver for compat in Project.toml

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/DataFrames.jl#1798]
Shouldn't we use proper semver in the `Project.toml`, instead of all the `>=` things that are in there right now?

For example, Tables.jl 0.2.0 was a breaking release (and properly tagged like that), but the way the dependency was specified here in DataFrames.jl as `Tables = ">= 0.1.15"` meant that the whole semver story didn't kick in and I think some of the tests broke. If the dependency here had been specified as `Tables = "0.1.15"` it would all have worked as it should, right?

This is not Tables.jl specific, it was just the example that popped up recently, I think this holds true for all the dependencies in the Project.toml.

I should say that this probably only works if the upstream packages actually conform with the julia interpretation of semver.

**Comment by bkamins** [comment]
I understand that @nalimilan made the decision to use `>=` as a transitory solution to possibilities of "Unsatisfiable requirements detected" problem and we should switch to more strict rules in the future.

**Comment by nalimilan** [comment]
My understanding is that the General registry has stopped adding upper bounds to dependencies that are below 1.0, so what we currently do is consistent with that. Anyway the problem with adhering strictly to semver before 1.0 is that dependencies make many "major" releases which generally break only a small subset of packages that depend on them. Having to update the bounds for all packages is just a nightmare as we don't have any automated mechanism to do that, and any package which isn't updated will block users to the previous version. This is what happened with StatsBase 0.30. It's much easier to fix only the packages that broke unfortunately.

IMO the only solutions to that mess are 1) stabilize the APIs and tag 1.0, 2) develop an automated system to increase bounds if tests pass with a new major release. That said, in the meantime, we could use stricter requirements for some dependencies which are more likely to break, e.g. because we use them intensively, such as Tables.jl.

**Comment by quinnj** [comment]
Yeah, ultimately I think it'd be better for most packages to tag 1.0, and then we all make sure to strictly adhere to semver.

**Comment by bkamins** [comment]
I think this can be closed given we now do not do `>=`.
