### ISSUE TITLE
Reexport policy

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#1842]
Currently we reexport CategoricalArrays.jl and Missings.jl.
I will add InvertedIndices.jl to reexport.
I think Missings.jl should stay, mostly for `passmissing` function.

The question is if we reexport CategoricalArrays.jl should we also reexport PooledArrays.jl?

**Comment by nalimilan** [comment]
+1 for InvertedIndices. PooledArrays is less essential since it only exports `PooledArray`, `PooledVector` and `PooledMatrix`. It's more important for CategoricalArrays since there are specific functions like `levels` (and possibly `levelvalue` and `levelcode`). Also we will probably be able to stop depending on PooledArrays directly and use a generic interface instead.
