### ISSUE TITLE
Rename `allowcomments` to `ignorecomments`

### ISSUE THREAD

**Issue by KwatME** [JuliaData/DataFrames.jl#1860]
![Screenshot from 2019-06-24 16-29-08](https://user-images.githubusercontent.com/7741548/60058433-397c7380-969d-11e9-8f72-d94fca7d8d7f.png)

The argument name suggests opposite behavior and can be confusing.

**Comment by bkamins** [comment]
As you noted in https://github.com/JuliaData/DataFrames.jl/issues/1602 this functionality is deprecated. In particular it is OK if someone wants to maintain it as a separate project. Our objective is to remove it from DataFrames.jl codebase, because it is not a part of what needs to be in DataFrames.jl package (having multiple ancillary functionalities in DataFrames.jl was needed in the past when the package ecosystem was not as mature, but now we tend to have one package provide only one consistent set of functionalities).

Therefore, as it was mentioned in the comment https://github.com/JuliaData/DataFrames.jl/issues/1602#issuecomment-439820149, please feel free to take the codes of `readtable`/`writetable` and make a package of them if you wish.

**Comment by nalimilan** [comment]
> Therefore, as it was mentioned in the comment [#1602 (comment)](https://github.com/JuliaData/DataFrames.jl/issues/1602#issuecomment-439820149), please feel free to take the codes of `readtable`/`writetable` and make a package of them if you wish.

Better file issues against CSV.jl. We really don't need an additional CSV parsing package in the ecosystem.
