### ISSUE TITLE
eachcol is not working as expected

### ISSUE THREAD

**Issue by jingpengw** [JuliaData/DataFrames.jl#1862]
it should return tuple of column name and value vector, but it seems not.
```julia
julia> df = DataFrame(x=4:7, y=11:14)
julia> df
4×2 DataFrame
│ Row │ x     │ y     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 4     │ 11    │
│ 2   │ 5     │ 12    │
│ 3   │ 6     │ 13    │
│ 4   │ 7     │ 14    │

julia> for (k,v) in eachcol(df)
       @show k, v
       end
(k, v) = (4, 5)
(k, v) = (11, 12)

```

julia 1.0.4
DataFrames v0.18.3

**Comment by bkamins** [comment]
It works as expected. `eachcol` is a standard function in Base since Julia 1.1. that is defined as:

> Create a generator that iterates over the second dimension of matrix A, returning the columns as views.

Therefore DataFrames.jl follows it with the following definition (taken from help on `eachcol`):

>  eachcol(df::AbstractDataFrame, names::Bool=false)
>  Return a DataFrameColumns that iterates an AbstractDataFrame column by column. If names is equal to false (the default) iteration returns column vectors. If names is equal to true pairs
  consisting of column name and column vector are yielded.

So `eachcol(df)` just produces you the columns:
```
julia> eachcol(df)
2-element DataFrames.DataFrameColumns{DataFrame,AbstractArray{T,1} where T}:
 [4, 5, 6, 7]
 [11, 12, 13, 14]
```

If you want to get `Pair`s of column name and column value then use the second positional argument and set it to `true` like this:
```
julia> eachcol(df, true)
2-element DataFrames.DataFrameColumns{DataFrame,Pair{Symbol,AbstractArray{T,1} where T}}:
 :x => [4, 5, 6, 7]
 :y => [11, 12, 13, 14]
```
