### ISSUE TITLE
[package code fancyness] Redundant code snippet

### ISSUE THREAD

**Issue by rapus95** [JuliaData/DataFrames.jl#1993]
https://github.com/JuliaData/DataFrames.jl/blob/fc2992c66ca4cde7bb828a356184654a025d154e/src/dataframe/dataframe.jl#L147-L152
This seems quite redundant.
I'd either make
```julia
colnames = keys(d) 
if isa(d, Dict) 
  colnames = sort!(collect(colnames)) 
end
```
or
```julia
if isa(d, Dict) 
  colnames = sort!(collect(keys(d)))
else
  colnames = keys(d)
end
```

**Comment by bkamins** [comment]
I would opt for the second approach. But in general (and here I assume is the source of your question) the issue is that `Dict` is sorted so we would have to decide if we want to sort `Dict` if we `push!` it do a `DataFrame` - right? So essentially it does not make much sense to sort the `keys(d)` in any scenario (it is easy to use `select!` to sort the column names for a `DataFrame` later anyway). And there it does not make much sense, as it would be a performance overkill. Do I get the source of your question right?

**Comment by rapus95** [comment]
that wasn't my intention and I got that sorting is only allowed, if the Dict has no order by itself (that's why it was checked). I never thought about whether that'd even useful. But I see it like you, doesn't seem useful to do at all.

**Comment by bkamins** [comment]
@nalimilan - any opinion here? In general the condition as it is used now is not very useful I think (`AbstractDict` other than `Dict` may or may not be ordered in general).

**Comment by nalimilan** [comment]
Sorting sounds like a good idea to me, it's better than getting an arbitrary order. So I'd just remove the redundant first `colnames = ` assignment.

**Comment by bkamins** [comment]
It can go as you propose, because it is non-breaking.
The only problem is that when @rapus95 does the `vcat`/`push!`/`append!` overhaul PR we should make it consistent.

In general before 1.0 a major thing that bothers me is the following (maybe in the end we will not change anything but it is a last moment to make this discussion):

* `AbstractDict` when passed to `DataFrame` does row expansion (even when mixing scalars and vectors)
* `NamedTuple` of vectors of equal length passed to `DataFrame` also creates multiple rows

Now `push!` treats them differently and creates a single row. The question is do we want to keep it this way.

**Comment by nalimilan** [comment]
It sounds OK for `push!` to interpret its argument as a single row, and for `append!` to interpret it as multiple rows, as that's the only possible meaning. So I'd say the current design is OK (unless I'm missing something).

**Comment by bkamins** [comment]
Agreed
