### ISSUE TITLE
Define `isapprox` for DataFrames

### ISSUE THREAD

**Issue by nicoleepp** [JuliaData/DataFrames.jl#1998]
`≈` (isapprox) doesn't exist for comparing two dataframes. Workaround is converting each to a Matrix for now and calling `isapprox` on those, but would be nice to have this implemented.

**Comment by nalimilan** [comment]
Makes sense. Do you feel like making a PR? You can take inspiration on the current definition of `==` and `isequal`.

**Comment by Sov-trotter** [comment]
@bkamins @nalimilan I would like to work on this. But I am confused as to where should I put the function.

**Comment by bkamins** [comment]
in the "Equality" secition in abstractdataframe/abstractdataframe.jl (below `Base.isequal`).

Initially I was hesitant to have this defined but after some thinking I think it is OK, because converting to a `Matrix` will not handle well what we want in DataFrames.jl for `isapprox` (as I think we should gracefully handle non-`Number` entries for it to be useful).

**Comment by Sov-trotter** [comment]
Indeed! But unfortunately, `isapprox` , isn't defined for other types. I wonder if it'd be right to have something like and `equals_ignorecase` to allow a minimal comparison of Strings ?

**Comment by bkamins** [comment]
I will comment on this in the PR.

**Comment by bkamins** [comment]
this is added on master
