### ISSUE TITLE
Allow mix of `Symbol` and `Pair` in `join`

### ISSUE THREAD

**Issue by nilshg** [JuliaData/DataFrames.jl#2001]
Currently we can do:
```
df1 = DataFrame(a = [1,2], b = ["a","b"], c = rand(2))
df2 = DataFrame(a = [1,2], B = ["a","b"], d = rand(2))

join(df1, df2, on = [:a => :a, :b => :B]) 
join(df1, df2, on = [:a]) 
join(df1, df2, on = [:b => :B], makeunique = true)
```
but it's not possible to do:
```
join(df1, df2, on = [:a, :b => :B])
```
This would be very convenient for cases where one has a large number of columns to match on, with only one or two that don't match and require a `Pair`.

**Comment by bkamins** [comment]
Makes sense and it should not be that hard to do.
Probably we should have something like internal `normalize_on` function that rewrites any `on` argument originally passed to be a `Vector{Pair}`, so that the later code can safely assume only one form (and this operation should be cheap relative to the other things `join` does).
Then in `normalize_on` we could make all the checks that the passed argument is valid.

Would you want to make a PR (if you do not have time I will have a look at this).

The only thing we have to be careful about when implementing it is that on master we allow joining more than two data frames in a single call (in which case we do not allow `Pairs`).

**Comment by bkamins** [comment]
See https://github.com/JuliaData/DataFrames.jl/pull/2006 for a fix
