### ISSUE TITLE
DataFrame constructor from Dict

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2119]
Tables.jl 1.0 supports dictionaries as tables.

This means that we now have two inconsistencies:
* DataFrames.jl sorts columns of `Dict` when it creates a `DataFrame` and Tables.jl not (which means that e.g. if you first cast a `Dict` to a `Tables.columntable` and only then you convert it to a `DataFrame` you get a different result than you would get by converting it directly)
* DataFrames.jl allows keys of any type (and converts them to `Symbol`)

@quinnj @nalimilan Do you think we should sync this?

**Comment by nalimilan** [comment]
Good catch. I'd say it would be better for Tables.jl to sort columns by name, since the order of entries in `Dict` is undefined. Then it would be consistent with DataFrames.

Regarding the conversion of keys to `Symbol`, it's not a problem if DataFrames is more permissive than Tables. But I'd say it also makes sense for Tables to try converting to `Symbol`. That change can happen at any time since it won't break anything.

**Comment by bkamins** [comment]
@quinnj - so it is a call to what you think now 😄. My biggest concern is that I want consistency between the packages.

**Comment by quinnj** [comment]
I'm not sure I quite understand the issue w/ sorting the columns; in my mind, order of Dict entries is undefined, so I wouldn't expect any kind of ordering guarantees when using it or converting between formats.

Tables.jl could probably do the Symbol casting; I'm on board with that. The Tables.jl implementation is very much v1, so I kind of expected there to be enhancements.

**Comment by nalimilan** [comment]
> I'm not sure I quite understand the issue w/ sorting the columns; in my mind, order of Dict entries is undefined, so I wouldn't expect any kind of ordering guarantees when using it or converting between formats.

It's just that we found it better to always sort columns according to their name, rather than using the undefined order in which `Dict` returns them. That sounds better in all respects: more natural and more predictable. Technically, moving from undefined to sorted isn't breaking so that can be done at any time.

**Comment by bkamins** [comment]
Just to be precise. We sort only `Dict`. For other `AbstractDict`s we do not touch the order of columns. So this is a kind of special case.

> Technically, moving from undefined to sorted isn't breaking so that can be done at any time.

Also it is relatively cheap as we do not expect millions of columns anyway.

For me it is important to have a decision if we keep sorting in DataFrames.jl as this is relevant for 1.0 release (as potentially moving from sorting to no-sorting is breaking).

**Comment by bkamins** [comment]
@nalimilan - I understand we can close this here. Later @quinnj can decide what to do in Tables.jl (currently Tables.jl says the order is undefined if I understand things correctly, so we are not in conflict with it).

**Comment by nalimilan** [comment]
Right. Maybe file an issue against Tables to discuss whether sorting would be a better behavior there (I think so).
