### ISSUE TITLE
Fix bounds in registry

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/DataFrames.jl#2137]
It would be good if the [bounds for DataFrames.jl](https://github.com/JuliaRegistries/General/blob/master/D/DataFrames/Compat.toml) in the registry could be cleaned up. 

I started with the most obvious problem https://github.com/JuliaRegistries/General/pull/10451, but looking at the `Compat.toml` for DataFrames.jl, there seem to be other problems as well:
- There are other bounds that end in `-*`, those should probably all be bounded properly.
- Starting with DataFrames.jl 0.14, there are quite a number of versions that declare themselves compatible with any pre 1.0 Tables version. Is that right? Presumably Tables 0.2 was breaking? Not sure, but might be worth checking that as well.

**Comment by bkamins** [comment]
See #10472. I am not sure about exact bounds on Tables 0.2 release (this probably would require a lot of tests to make sure we set bounds correctly for each version), but I think it is enough to make sure that we guarantee that Julia does not install an older version of DataFrames.jl instead of the latest release.

**Comment by bkamins** [comment]
Things should be fixed now (please reopen the issue if this is not the case)
