### ISSUE TITLE
review consistency of `@view` semantics

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/DataFrames.jl#2143]
I noticed today that `@view df[1:1, :]` gives you a `SubDataFrame`, which is very nice, however `@view df[1, :]` gives you a `DataFrameRow`.  This is inconsistent with `AbstractArray` behavior, since `@view A[1, :]` still returns a view, where `A` is a matrix.

Perhaps it's worth reviewing the consistency of view behaviors before 1.0?  Anybody aware of other similar issues?

**Comment by bkamins** [comment]
`DataFrameRow` is a view. Actually this difference is exactly due to consistency with Base reasons.

`DataFrameRow` is 1-dimensional, and `SubDataFrame` is 2-dimensional, so this is the same as with arrays, where `@view A[1, :]` gives you a 1-dimensional object while `@view A[1:1, :]` gives you a 2-dimensional object.

(I am closing this, but please do not hesitate reporting such concerns in the future as it is better to discuss such things before 1.0 release rather than letting them slip through)

**Comment by bkamins** [comment]
No problem - as you see on Slack the issues is not that simple and well deserves a discussion 😄.
