### ISSUE TITLE
Performance of allunique

### ISSUE THREAD

**Issue by clintonTE** [JuliaData/DataFrames.jl#2153]
`allunique` seems to run very slowly when iterating on rows. Not a big issue since it's easy to work around, but the performance difference was large enough I thought I would post it here.

```Julia
function alluniquemwe(i::Int)
  df = DataFrame(x1=rand(i), x2=rand(i))

  print("allunique: ")
  @time println("$(allunique(eachrow(df)))")

  print("roughly equivalent to allunique: ")
  @time println("$(length(groupby(df, [:x1,:x2]))==size(df,1))")
end

alluniquemwe(10^6)
```

Output:
```
allunique: true
  3.886576 seconds (50.99 M allocations: 1.026 GiB, 7.27% gc time)
roughly equivalent to allunique: true
  0.079434 seconds (64 allocations: 46.150 MiB)
```

**Comment by bkamins** [comment]
Thank you for reporting this.

Going to the issue. What you observe is to be expected and nothing can be done about it unfortunately due to type instability.

You should rather `nonunique` function (which is fast and intended exactly for this application) or if you need to use an iterator in performance-sensitive code use `Tables.namedtupleiterator` instead of `eachrow`.

The purpose of `eachrow` is to provide an iterator over rows of a data frame that avoids compilation (which is mostly needed for very wide data frames, in which case `Tables.namedtupleiterator` can be very slow to compile):

```
julia> function alluniquemwe(i::Int)
         df = DataFrame(x1=rand(i), x2=rand(i))

         print("allunique: ")
         @time println("$(allunique(eachrow(df)))")

         print("allunique BK 1: ")
         @time println("$(allunique(Tables.namedtupleiterator(df)))")

         print("allunique BK 2: ")
         @time println("$(!any(nonunique(df)))")

         print("roughly equivalent to allunique: ")
         @time println("$(length(groupby(df, [:x1,:x2]))==size(df,1))")
       end
alluniquemwe (generic function with 1 method)

julia> alluniquemwe(10^6)
allunique: true
  5.133099 seconds (51.21 M allocations: 1.031 GiB, 19.64% gc time)
allunique BK 1: true
  0.351259 seconds (69 allocations: 65.171 MiB, 15.95% gc time)
allunique BK 2: true
  0.132978 seconds (17 allocations: 16.584 MiB)
roughly equivalent to allunique: true
  0.140023 seconds (56 allocations: 23.262 MiB)
```

**Comment by clintonTE** [comment]
Great, and thanks for the informative and helpful response.

**Comment by bkamins** [comment]
Just one more comment. The benefit of `eachrow` is that it produces `DataFrameRow` which is a view of the row of a data frame. Which means you can alter the source data frame while iterating it.
