### ISSUE TITLE
Shall `mapcols` be deprecated?

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2186]
```
@deprecate `mapcols(fun, df)` select(df, names(df) .=> fun .=> names(df))
```
the only benefit of `mapcols` is that it allows for `do` block, so maybe we should leave it.

CC @nalimilan @oxinabox

**Comment by nalimilan** [comment]
I guess the main reason to remove it would be to reduce the number of functions ending in "cols" (the other one being `insertcols!`). Otherwise it doesn't really hurt to have it.

**Comment by bkamins** [comment]
Well - we want to deprecate `aggregate` to reduce the number of functions we expose.

What difference do you see between `aggregate` and `mapcols` here?.

**Comment by nalimilan** [comment]
`aggregate` is a very generic term which means different things in other languages. `mapcols!` is more explicit. But I'm not particularly attached to it. IIRC it mainly exists because it used to be `map` when DataFrames were column-oriented, but it may not have a very good reason to exist. I imagine the main use case is standardizing columns.

**Comment by bkamins** [comment]
OK - let us just keep it. I am closing the issue.

@oxinabox - please reopen (or comment to reopen - I am not sure if you have rights to reopen issues in this repo) if you feel it is worth to deprecate it.
