### ISSUE TITLE
Why does categorical!(df::DataFrame, ...) exist?

### ISSUE THREAD

**Issue by matthieugomez** [JuliaData/DataFrames.jl#2192]
I don't understand why `categorical(df, cols)` exists. 

If it is about applying a function (`categorical`) to multiple columns of a dataframes, there should be a way to do it for any function, not just `categorical` (I guess that's what `transform` is about?).

I'm not following the package closely, so sorry if this was discussed somewhere.

**Comment by bkamins** [comment]
Thank you for raising this point (we have a similar case with `allowmissing` and `disallowmissing`). Simply in the past our API was much less flexible.

It has one minor functionality that:
1. by default it converts string column
2. it can take type as a column selector

But apart from this it is true that roughly (I am dropping some corner cases):
```
@deprecate categorical(df, cols) transform(df, cols .=> categorical .=> cols)
```
and
```
@deprecate categorical!(df, cols) transform!(df, cols .=> categorical .=> cols)
```

Having said this, I do not see a huge problem to keep `categorical` and `categorical!` as convenience functions. We define such functions for most common transformations, so that users have an easier life. @nalimilan - what do you think?

**Comment by nalimilan** [comment]
Yes I think it makes sense to have some convenience functions. That's the clearest for `allowmissing` as it's a very common need, but `categorical` is already exported since it exists in CategoricalArrays, so adding a new method isn't very costly.

For other functions, `mapcols` can also be used instead of `transform`. I guess we could add `mapcols!` for in-place operation.

**Comment by matthieugomez** [comment]
Thanks for the explanation! I think it'd be better to have only one way to do things, but that's your choice! I appreciate all the improvement happening these days, by the way. Thanks for your work!
