### ISSUE TITLE
Tag a new release to reflect [compat] CategoricalArrays = "0.8" update

### ISSUE THREAD

**Issue by ablaom** [JuliaData/DataFrames.jl#2204]
Said update has happened on master, but not been tagged for release, as far as I can tell. 

Causing problems for packages that have  CategoricalArrays="0.8" in their [compat] but want to use DataFrames for testing only.

**Comment by ablaom** [comment]
Case-in-point is repo referenced above.

**Comment by bkamins** [comment]
We will tag a release of DataFrames.jl soon. Mostly #2199 needs to be finished. But we needed to release CategoricalArrays.jl before the release of DataFrames.jl so we are now in a transition period (you have the same situation with CSV.jl).

I am closing this, because this issue is tracked and will be resolved soon.

**Comment by ablaom** [comment]
Thanks for the prompt response. Appreciate it.
