### ISSUE TITLE
any or all in dropmissing

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaData/DataFrames.jl#2219]
Currently, `dropmissing` drops a row if *any* of the columns contains a missing. 
I would like to have the option of dropping only if *all* columns are missings, something which is not clear how to achieve at the moment (use a filter?)  
Therefore I suggest to add a keyword arg, e.g.  `mode=:any` or `mode=:all`.

**Comment by bkamins** [comment]
Yes - currently you should use `filter` for this.

If the table is wide write:
```
filter(x -> !all(ismissing, x), df)
```
if the table is not wide then this will be faster (it requires master of DataFrames.jl):
```
filter(AsTable(:) => x -> !all(ismissing, x), df)
```

Here is an example (again - it requires master):
```
julia> df = repeat!(DataFrame(x=[1,missing,2,missing], y=[missing,1,2,missing]), 10^6);

julia> @time filter(x -> !all(ismissing, x), df);
  1.694034 seconds (22.34 M allocations: 532.620 MiB, 8.46% gc time)

julia> @time filter(AsTable(:) => x -> !all(ismissing, x), df);
  0.386947 seconds (2.51 M allocations: 312.596 MiB, 15.33% gc time)
```

I am not sure if adding a special functionality to `dropmissing` is justified as what you request is needed very rarely. I will keep the issue open though, as maybe other people will feel otherwise.

**Comment by nalimilan** [comment]
Given that it's relatively simple to achieve, I vote for not adding specific support for this to `dropmissing`.

**Comment by bkamins** [comment]
OK - if there are no serous votes against it I will close this issue in a few days.

**Comment by bkamins** [comment]
ok - closing this.
