### ISSUE TITLE
Confusing error message when filtering a grouped data frame with a Vector{Union{Missing, Bool}}

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaData/DataFrames.jl#2242]
```julia
julia> df = DataFrame(a = [1, 1, 2, 2], x = 1:4);

julia> gdf = groupby(df, :a);

julia> gdf[[true, missing]]
ERROR: ArgumentError: Invalid index: true of type Bool
Stacktrace:
 [1] to_index(::GroupedDataFrame{DataFrame}, ::Array{Union{Missing, Bool},1}) at /Users/bieganek/.julia/packages/DataFrames/3ZmR2/src/groupeddataframe/groupeddataframe.jl:349
 [2] to_indices at ./indices.jl:325 [inlined]
 [3] to_indices at ./indices.jl:322 [inlined]
 [4] getindex(::GroupedDataFrame{DataFrame}, ::Array{Union{Missing, Bool},1}) at /Users/bieganek/.julia/packages/DataFrames/3ZmR2/src/groupeddataframe/groupeddataframe.jl:302
 [5] top-level scope at REPL[92]:1
```

**Comment by bkamins** [comment]
This is expected - indexing with `Bool` is allowed only when indexing vector is `<: AbstractVector{Bool}` otherwise index `true` is invalid. It has nothing to do with `missing` entry. See e.g.:
```
julia> gdf[[true, false]]
GroupedDataFrame with 1 group based on key: a
First Group (2 rows): a = 1
│ Row │ a     │ x     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 1     │
│ 2   │ 1     │ 2     │

julia> gdf[Any[true, false]]
ERROR: ArgumentError: Invalid index: true of type Bool
```
The error message is what Julia Base produces in such case - it is not something that is DataFrames.jl specific.

Note that this is the same in Base (the error message is a bit different, but the rule is the same):
```
julia> x[[true, false]]
1-element Array{Int64,1}:
 1

julia> x[Any[true, false]]
ERROR: BoundsError: attempt to access 2-element Array{Int64,1} at index [Any[true, false]]
```

So I would close this unless you have a proposal of a better error message (in which case we can try to intercept the default error message and substitute it). Note though that the current error message is technically correct - it is disallowed to use value of type `Bool` as a single indexing expression as in:
```
julia> gdf[true]
ERROR: ArgumentError: invalid index: true of type Bool
```
(in this case for sure I would not want to change the error message)

**Comment by CameronBieganek** [comment]
Hmmm, this is definitely one of those cases where Julia's error messages are very suboptimal. If a reasonably experienced Julia user has trouble figuring out what's going on, just imagine how confusing it would be for a beginner. Maybe I'll open an issue in JuliaLang.

**Comment by bkamins** [comment]
The error message probably should have an additional comment
> indexing with `Bool` is only allowed if they are passed in `AbstractArray{Bool}` of size matching the size of the indexed object

**Comment by bkamins** [comment]
I have looked into it again. Unfortunately it seems that in order to fix it a change in Base is required, so I close it here.
