### ISSUE TITLE
show all columns at HTML in Jupyter notebook

### ISSUE THREAD

**Issue by marketneutral** [JuliaData/DataFrames.jl#2293]
I am working in Jupyter/IJulia. I would like to be able to show the full number of columns rendered in HTML.

I am trying

```
show(MIME("text/html"), df, allcols=true)
```

which throws

```
MethodError: no method matching show(::MIME{Symbol("text/html")}, ::DataFrame; allcols=true)

Stacktrace:
 [1] top-level scope at In[341]:1
```

I can render the dataframe as text with `show(df, allcols=true)`, but what I need/want is HTML.

A workaround is to set `ENV["COLUMNS"]` to something very large and then I can see all columns, but this seems like a hacky workaround.

Is there a way to render the full dataframe in HTML just using `show`? Thank you.

**Comment by bkamins** [comment]
If you want it rendered in Jupyter Notebook, then setting `ENV["COLUMNS"]` is the standard way to do it. The reason is that Jupyter Notebook not only renders HTML but also LaTeX and due to this it has a special handling of IO (in particular it uses `ENV["COLUMNS"]` internally to determine output width).

However, if you need a HTML output sent to an `IO` to which a variable called e.g. `io` points then just do:
```
show(io, MIME("text/html"), df)
```
