### ISSUE TITLE
Deprecations in DataFrames.jl

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2344]
As in Julia 1.5 the deprecations by default will not be printed I propose to stop deprecations for:
* `push!`
* `append!`
* `sort`
* `join` and new join functions related
* `getindex`
* `setindex!`
* `setproperty!`
* `view`
* `DataFrame`
* `show`
* `showall`
* `colwise`
* `deletecols`
* `deletecols!`
* `eltypes`
* `permutecols!`
* `names!`
* `describe`
* `stackdf`
* `meltdf`
* `lastindex`
* `insertcols!`
* `eachcol`
* `groupvars`
* `aggregate`
* `deleterows!`
* `by`
* `map`

Deprecations that will be kept for one release:
* `DataFrame!`

Also I would propose to introduce a policy: if in release `X` we deprecate something we remove it in release `X+1`.

As a side benefit the DataFrames.jl will be significantly "thinned down" by removal of the deprecations.

If we agree to this I will make a PR (but before doing this I would like to have an agreement that it should be done, as it will be 1000+ deletions PR and many additions of the tests that were pending have to be made). Thank you!

**Comment by quinnj** [comment]
I'm definitely in favor; I've always been a strong advocate of the "deprecations last for X+1 release" policy

**Comment by bkamins** [comment]
The number of 👍 will hopefully influence the opinion of @nalimilan who is conservative here (and I fully understand his perspective as we have discussed this numerous times). Simply I believe that post Julia 1.5 deprecations will have close to no value to users (who are not likely to turn on warnings) and for package maintainers X+1 time should be enough to notice changes in CI (it is at least several months, probably more in the future in case of DataFrames.jl).

**Comment by nalimilan** [comment]
So in the future (after 1.0) we will remove deprecations in the major release after they have been introduced. The current period is special because of the change in Julia 1.5 which turns warnings into silently working code. Something that's clear is that we shouldn't keep old deprecations as they are, as people wouldn't get any notice that they are using functions that have been deprecated for ages.

My preference would be to turn them into plain errors, so that people who haven't followed our relatively short release cycle and find semi-old examples on the Web are not too confused. But if you want to remove them that's OK too.

**Comment by bkamins** [comment]
A good point:
1. I will turn into errors what can be reasonably made an error and write a test for it (it makes sense to do so anyway as these mostly will be errors - just an informative error message should be printed rather than e.g. `MethodError` 😄)
2. For other things that are hard to turn into an error - I will just remove them.

**Comment by bkamins** [comment]
#2350 is good for a review. As a bonus on my machine these changes reduce DataFrames.jl load time by 0.1s (not much, but noticeable).
