### ISSUE TITLE
Performance issue when looping over DataFrame column

### ISSUE THREAD

**Issue by Ankur-deDev** [JuliaData/DataFrames.jl#2348]
Hi,

I bumped into performance issues that I could not
understand and created the minimal simple example below.
The code below provides two functions which basically loop over a column,
in one case it is a column of a DataFrame and in the other case it is a Vector.
I would expect both functions to have similar benchmark results, but it turns out that they are very different.

```
# Function to sum a dataframe column.
function test_d(d::DataFrame)
  # Get dataframe size.
  data_size = size(d)[1]

  # Get column of weights.
  wcol = d[:, :WEIGHT]

  # Initialize sum.
  wsum::Float64 = 0.0

  # Loop over column.
  for i in 1:data_size
    # Update sum.
    wsum = wsum + wcol[i]
  end

  # Return result.
  return wsum
end

# Function to sum vector values.
function test_v(v::Vector{Float64})
  # Get vector size.
  data_size = size(v)[1]

  # Initialize sum.
  wsum::Float64 = 0.0

  # Loop over vector.
  for i in 1:data_size
    # Update sum.
    wsum = wsum + v[i]
  end

  # Return result.
  return wsum
end
```

The benchmark results are the followings:

```
# Define a random vector of Float64.
wvec = rand(1000000)

# Define a Dataframe.
df = DataFrame(WEIGHT=wvec)

# Benchmark 'test_d'.
@benchmark test_d(df)
BenchmarkTools.Trial: 
  memory estimate:  68.66 MiB
  allocs estimate:  3999492
  --------------
  minimum time:     69.594 ms (4.16% GC)
  median time:      72.563 ms (4.84% GC)
  mean time:        72.476 ms (6.42% GC)
  maximum time:     83.378 ms (8.30% GC)
  --------------
  samples:          69
  evals/sample:     1

# Benchmark 'test_v'.
@benchmark test_v(df[:,:WEIGHT])
BenchmarkTools.Trial: 
  memory estimate:  7.63 MiB
  allocs estimate:  2
  --------------
  minimum time:     1.586 ms (0.00% GC)
  median time:      1.633 ms (0.00% GC)
  mean time:        2.087 ms (21.30% GC)
  maximum time:     6.055 ms (67.82% GC)
  --------------
  samples:          2396
  evals/sample:     1

```

The above numbers seem to indicate that the function taking a DataFrame as
argument is 40 times slower and performs an inexplicable number of memory allocations.
I would like to understand what is the root cause of such difference in performance.
Would you please help me?

This was performed with DataFrames v0.21.5 under Julia 1.5.0.

**Comment by bkamins** [comment]
This is a known thing and it is expected to work this way as `DataFrame` is type unstable. https://github.com/bkamins/Julia-DataFrames-Tutorial/blob/master/11_performance.ipynb in the tutorial to DataFrames.jl explains what to do with it (essentially - either add type annotation or use a barrier function).

In particular if you would use `combine`, `select` or `transform` they automatically do this under the hood (and this is the difference between imperative and declarative use of DataFrames.jl). Also this is the reason where `Tables.columntable` or `Tables.namedtupleiterator` can be used to make things type stable (if you prefer to use DataFrames.jl in imperative style).

Now why DataFrames.jl is type-unstable? Because it allows the user to change its schema in-place (the schema is: number of columns, names of columns, eltype of columns) and this is what often users want.

**Comment by Ankur-deDev** [comment]
Thanks a lot for your quick answer, the link is very helpful.
