### ISSUE TITLE
Add ByRow() and ByCol() to have explicit operations row-wise and column-wise

### ISSUE THREAD

**Issue by ppalmes** [JuliaData/DataFrames.jl#2441]
- if we want columnwise or row-wise iteration, perhaps we can use: 
```julia
rowmean = select(df,All(r"x*") => ByRow(mean))
colmean = select(df,All(r"x*") => ByCol(mean))
```
- while we know that dataframes prefer column oriented operations, it will be great for symmetry if we have column and row iterators in the expression.
- currently, if you do 
```
select(df,AsTable(All(r"x*")) => argmax => m) # not correct but no error and no idea what is this
select(df,AsTable(All(r"x*")) => ByRow(argmax) => m) # correct one but it is easy to forget ByRow
```
- maybe we restrict the syntax to be: select(df, ColumnFilter => ByRow/ByCol => NewNames)
- if there is no explicit ByRow or ByCol, the pattern is not clear and should reject it.

**Comment by bkamins** [comment]
> `select(df,AsTable(All(r"x*")) => argmax => m)`

this is correct only if `r"x*"` selects exactly one column. Otherwise it will be invalid

---

In general --- at this stage we will not change a design here. `ByRow` has to be explicit and `ByCol` that you propose is not needed - use broadcasting to get this behavior (and in general - is a different operation than not specifying `ByCol` or `ByRow`).
