### ISSUE TITLE
insertcols!(df, values => :name )

### ISSUE THREAD

**Issue by adkabo** [JuliaData/DataFrames.jl#2512]
The [other functions have](https://bkamins.github.io/julialang/2020/07/17/pair.html) `values => :name` but `insertcols!` has `:name => values`. I would prefer the consistency of `values => :name` everywhere.

**Comment by bkamins** [comment]
No functions have `values => :name`. The syntax is `source => transformation => target` (no `value` there is allowed).

Indeed, as discussed in the linked post `insertcols!` and `DataFrame` constructor follow `name => value` convention which is a bit unfortunate, but this is made so that they are consistent with the `Dict` constructor and `NamedTuple` creation style via kwargs.

Note the following (note that two different constructors are invoked in both cases):
```
julia> DataFrame(;:a => 1, :b => 2)
1×2 DataFrame
│ Row │ a     │ b     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 2     │

julia> DataFrame(:a => 1, :b => 2)
1×2 DataFrame
│ Row │ a     │ b     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 2     │
```

Indeed it is a bit unfortunate, but I think we will leave it as is, as changing this would be breaking and possibly inconvenient (though it would be more consistent indeed).

**Comment by adkabo** [comment]
Ah you're right, `value => :name` isn't quite it.  As you say, I was thinking of the note

> In the 0.22 release of DataFrames.jl target_column_name => aggregation_function style will be deprecated in favor of aggregation_function => target_column_name to make it more consistent with other functions allowing => in combination with a transformation function.

as well as `rename(:from => :to)` in that direction.

**Comment by bkamins** [comment]
Yes, these things are hard to get 100% consistent as there are many things to consider:

> `aggregation_function => target_column_name`

The point is that the first argument is a function (not a value)

> `rename(:from => :to)`

The same is allowed in `select` etc..

In this case the rule is that the first element is source column.

---

As a general comment. When we see:

```
a => b
```
it must be unambiguous in `select` etc. what it means. If we allowed `a` to be a value then writing `:a => :b` might mean:
1. take value `:a` and broadcast it to create a column `:b`, or
2. rename column from `:a` to `:b`

we have judged that the second is more often useful, thus the first is disallowed.
