### ISSUE TITLE
Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated

### ISSUE THREAD

**Issue by Beramos** [JuliaData/DataFrames.jl#2532]
This deprecation warning is very unclear to me since the only thing I'm doing is the following,

![image](https://user-images.githubusercontent.com/11618908/98672842-b83b8480-2356-11eb-8913-a1d2ec7b33cd.png)

I don't see why this slicing should lead to deprecation warnings.

```
Julia version 1.3.1

CSV v0.7.7
DataFrames v0.21.8
GalvanostatLNP v0.1.0
OrdinaryDiffEq v5.42.3
```

**Comment by bkamins** [comment]
It should print a deprecation because the syntax `DF_0Hz_short["<Ewe>/V"]` is not supported. It was supported many years ago, and we left a depwarn for some time for the users to accommodate their legacy code. In 2 weeks from now it will error.

The correct syntax is `DF_0Hz_short."<Ewe>/V"` or equivalently `DF_0Hz_short.[!, "<Ewe>/V"]` or if you want to copy the vector you extract from the data frame: `DF_0Hz_short.[:, "<Ewe>/V"]`.

**Comment by Beramos** [comment]
Ok thanks, that is clear

Op di 10 nov. 2020 13:22 schreef Bogumił Kamiński <notifications@github.com

**Comment by bkamins** [comment]
Maybe as an additional comment - `DataFrame` is a 2-dimensional object, so for consistency when using indexing syntax `df[...]` it requires two dimensions to be passed. It is not much more typing but avoids confusion.
