### ISSUE TITLE
 ArgumentError: syntax df[column] is not supported use df[!, column] instead

### ISSUE THREAD

**Issue by liwen-alt** [JuliaData/DataFrames.jl#2570]
A is matrix
A = sparse(B)
    indextuple = findnz(A)
    df = DataFrame()
    df[:xindex] = indextuple[1]
    df[:yindex] = indextuple[2]
    df[:issample] = 0
![image](https://user-images.githubusercontent.com/63285313/100868631-d2403100-34d6-11eb-8fa9-82daa828ea3a.png)
![image](https://user-images.githubusercontent.com/63285313/100868824-20553480-34d7-11eb-8dda-a9fbcbc85c32.png)
![image](https://user-images.githubusercontent.com/63285313/100868879-3105aa80-34d7-11eb-8e31-4d85780b843d.png)

**Comment by bkamins** [comment]
The error is exactly what it says `df[:xindex]` is not a valid index into a data frame. `DataFrame` is a 2-dimensional object so you need to use two dimensions to index into it.

The easiest to write is `df.xindex` using a property setting.

Now similarly you need to write e.g. `df[!, :issample] .= 0` (with broadcasting `.`) as otherwise you will have a dimension mismatch error exactly like in Julia Base.

All this is in detail explained in https://dataframes.juliadata.org/v0.18.3/index.html and in particular in https://dataframes.juliadata.org/v0.18.3/lib/indexing.html.
