### ISSUE TITLE
0.22 breaks getindex(::DataFrame, ::Array{Symbol,1})

### ISSUE THREAD

**Issue by fredcallaway** [JuliaData/DataFrames.jl#2579]
I was very surprised to find that this code no longer works with the newest version:

```
julia> df = DataFrame(x=[1,2,3], y=[4,5,6])
julia> df[[:x, :y]]
```

Was this intentional? It isn't mentioned in the release notes.

**Comment by bkamins** [comment]
It is not mentioned because this syntax has not been supported for more than a year now (and it was announced that it will be removed over 2 years ago). We just kept throwing a deprecation warning for some time in order to help people migrate to a currently supported syntax that is consistent.

`df[[:x, :y]]` is not supported because `DataFrame` is not a collection of columns. It requires two-dimensional indexing, so either do e.g. `df[:, [:x, :y]]` or `select(df, [:x, :y])` if you prefer dplyr-like style.
