### ISSUE TITLE
Tables.jl constructor

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2589]
@quinnj following what I asked on Slack:

> https://tables.juliadata.org/stable/#Implementing-the-Interface-(i.e.-becoming-a-Tables.jl-source)-1 allows a type to define Tables.rows or Tables.columns maybe in https://github.com/JuliaData/DataFrames.jl/blob/main/src/other/tables.jl#L55https://github.com/JuliaData/DataFrames.jl/blob/main/src/other/tables.jl#L55 we should check if the passed table defines row- or column- access style and have two code paths?

What is your opinion on this? (maybe it is not a problem?)

**Comment by nalimilan** [comment]
I don't really understand the problem. Won't `Tables.columns` use the fastest path? Anyway we need column vectors in the end.

**Comment by quinnj** [comment]
Yes, @nalimilan is right here; it doesn't really matter if the source defines `Tables.rows` or `Tables.columns` since `DataFrame` needs column vectors anyway. If a source only implements `Tables.rows`, there is a very efficient fallback in Tables.jl defined that "builds columns" from the rows provided.
