### ISSUE TITLE
Why can only 8 columns be displayed in JupyterLab

### ISSUE THREAD

**Issue by Jianqing001** [JuliaData/DataFrames.jl#2619]
input: df=CSV.read("E:\Study\Titanic.csv",DataFrame)
output:
891 rows × 12 columns (omitted printing of 8 columns)
.......

But my screen can actually show a lot more
The portion that displays the data takes up only half of the text box

**Comment by bkamins** [comment]
As you can read in the [Getting started](https://dataframes.juliadata.org/stable/man/getting_started/#Installation) section of the manual this is controlled by `ENV["COLUMNS"]` and `ENV["LINES"]` variables. The reason is that JupyterLab does not pass information to the Julia process how big is the browser window you use, so you - unfortunately - have to set this value manually if you have very wide screen.

Please note that this behavior is not DataFrames.jl specific. If you run any Julia command in JupyterLab that displays something you will get the same behavior.

Please consider asking questions on https://stackoverflow.com/questions/tagged/julia or https://discourse.julialang.org/ as GitHub is mostly intended for tracking bugs and feature requests. Thank you!
