### ISSUE TITLE
select treats renamed columns as separate from the old named ones. 

### ISSUE THREAD

**Issue by jonasjonker** [JuliaData/DataFrames.jl#2631]
the `:` has different behaviour in `select` function based on if columns are renamed or not.

Given the following DataFrame:
```julia
julia> ta = [1 2 3 4
             2 3 4 5]

julia> df = DataFrame(ta, :auto)

julia> rename!(df, ["a b", "c d", "ef", "gh"])
2×4 DataFrame
 Row │ a b    c d    ef     gh    
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │     1      2      3      4
   2 │     2      3      4      5
```
and this behavior of the double colon `:`

```julia
julia> select(df, "gh", :)
2×4 DataFrame
 Row │ gh     a b    c d    ef    
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │     4      1      2      3
   2 │     5      2      3      4
```
I would expect the following behavior when some columns are renamed: 

### expected behavior
```julia
julia> select(df, "a b" => :ab, "c d" => :cd, :)
2×6 DataFrame
 Row │ ab     cd     ef     gh    
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │     1      2      3      4
   2 │     2      3      4      5

```
However the "old" columns are added after the renamed columns as well.
### actual behavior 
```julia
julia> select(df, "a b" => :ab, "c d" => :cd, :)
2×6 DataFrame
 Row │ ab     cd     a b    c d    ef     gh    
     │ Int64  Int64  Int64  Int64  Int64  Int64 
─────┼──────────────────────────────────────────
   1 │     1      2      1      2      3      4
   2 │     2      3      2      3      4      5

```
My assumption is that this is because `select` does a `transform` under the hood.

```julia
transform(df, "a b" => :ab, "c d" => :cd)
2×6 DataFrame
 Row │ a b    c d    ef     gh     ab     cd    
     │ Int64  Int64  Int64  Int64  Int64  Int64 
─────┼──────────────────────────────────────────
   1 │     1      2      3      4      1      2
   2 │     2      3      4      5      2      3
```

But I would like to argue that this is a bug,

```julia
(env) pkg> status
Status `~/env/Project.toml`
  [a93c6f00] DataFrames v0.22.5
```

**Comment by bkamins** [comment]
`select` does not do `transform` under the hood. In `select`, `transform`, and `combine` using `:` means:

> add in the place where `:` is placed all columns of the source data frame that have not been added to the result; the adding is based on column name (not contents)

Why it works like this:
In general we allow for potentially very complex transformations in `select` etc. - columns can be created, renamed, added in any order. In order to keep the rules simple (so that users can build a correct mental model of what is going on and not too much magic happens) the approach is that columns are processed left to right and are identified by on their name in target data frame.

I agree that in your particular case it seems better to do what you propose, but if you consider a wider context (i.e. that in one `select` you can have dozens of different transformations combined) keeping the rules consistent without any special cases is I believe better.

How to resolve your case:
```
select(df, "a b" => :ab, "c d" => :cd, Not(["a b", "c d"]))
```

**Comment by bkamins** [comment]
Just as additional comment. What you want is done by the `rename` function (if you want only column renaming). Then there is no need to pass `:` at all.

And regarding why things work now as they do is the following example:
```
select(df, :a => :b, :a => :c)
```
which works and is accepted producing two identical columns. What this shows is `:a => :b` works "as" column rename, but actually it is a column transformation using `identity` function.

**Comment by jonasjonker** [comment]
Thanks for you answer! It was very clear.
