### ISSUE TITLE
I am not understanding why `CategoricalArrays.CategoricalArray` this? but we should get this `CategoricalArray`

### ISSUE THREAD

**Issue by RohitRathore1** [JuliaData/DataFrames.jl#2705]
```
julia> using CategoricalArrays
julia> cv = CategoricalArray(v)
6-element CategoricalArray{String,1,UInt32}:
 "Group A"
 "Group A"
 "Group A"
 "Group B"
 "Group B"
 "Group B"
Subexpression:
│ 
│ cv = CategoricalArray(v)
│ 
│ Evaluated output:
│ 
│ 6-element CategoricalArrays.CategoricalArray{String,1,UInt32}:
│  "Group A"
│  "Group A"
│  "Group A"
│  "Group B"
│  "Group B"
│  "Group B"
│ 
│ Expected output:
│ 
│ 6-element CategoricalArray{String,1,UInt32}:
│  "Group A"
│  "Group A"
│  "Group A"
│  "Group B"
│  "Group B"
│  "Group B"
│ 
│   diff =
│    Warning: Diff output requires color.
│    6-element CategoricalArray{String,1,UInt32}:
│     CategoricalArrays.CategoricalArray{String,1,UInt32}:
│     "Group A"
│     "Group A"
│     "Group A"
│     "Group B"
│     "Group B"
│     "Group B
```

**Comment by bkamins** [comment]
@mortenpi 

The problem is that it seems that although @RohitRathore1 has done `using CategoricalArrays` Documenter.jl keeps some separate environment for evaluation of REPL output so it produces `CategoricalArrays.CategoricalArray{String,1,UInt32}` instead of `CategoricalArray{String,1,UInt32}` as if CategoricalArrays.jl was not loaded in the evaluation scope.

Similar things happen when writing tests with Test.jl but then adding `using CategoricalArrays` resolves the issue, while here it seems not to be so.

Does Documenter.jl also require `using CategoricalArrays` to be added to [setup code](https://juliadocs.github.io/Documenter.jl/stable/man/doctests/#Setup-Code) in such cases.

Thank you!

**Comment by bkamins** [comment]
you have to do `using CategoricalArrays` in make.jl
