### ISSUE TITLE
Are there any plans to enable GPU computations similar to cuDF?

### ISSUE THREAD

**Issue by AdrianAntico** [JuliaData/DataFrames.jl#2713]

**Comment by bkamins** [comment]
Currently not.
Could you please report in what use cases do you see that what we provide currently in `main` has a significant performance bottleneck?

In particular - if you are working with small tables that have few rows and few columns and a fixed schema (roughly sub 1GB of data), but want to process millions of such tables very fast then DataFrames.jl is not optimized for this use case and never will be because of its design (which assumes wide and tall tables with dynamically changing schema).
In such a case I would recommend you to rather use some type-stable alternative implementing Tables.jl interface.

However with sub 1GB of data the processing is very fast anyway so unless you have millions of such operations the difference will not be noticeable in practice and most of the cost will be compilation cost not processing cost.

**Comment by AdrianAntico** [comment]
@bkamins I've been keeping track of Julia DataFrames.jl on the h2o benchmark webpage and it looks good as is. I am actually just curious if there were any plans for implementing any GPU operations similar to how Rapids cuDF works. AFAIK the cuDF package is the only one that does utilize GPU for data frames but it's only available for linux users last time I checked.

**Comment by bkamins** [comment]
> I've been keeping track of Julia DataFrames.jl on the h2o benchmark webpage and it looks good as is

`main` is much faster than what is reported currently there.

As commented - it is unlikely we will add GPU support in the near future.

**Comment by quinnj** [comment]
I believe GPU support _could_ be orthogonal to anything directly in the DataFrames.jl library; for example, the [CUDA.jl](https://github.com/JuliaGPU/CUDA.jl) package provides an abstract array interface to doing GPU compute. DataFrames.jl already allows passing in any kind of AbstractVector as columns, so, in theory, things could "just work". There might be cases where we can try to "keep" arrays on the GPU, but all it takes is someone willing to try things out and report back on what works and what doesn't.

**Comment by AdrianAntico** [comment]
@bkamins I've tested out some of the operations from the H2O benchmark and I'm seeing similar timings for first and second runs. Does DataFrames enable parallelism under the hood and if so is there a way to set the number of cores (or threads) before running the code? I have found that settings the number of threads to the max amount with data.table tends to slow down the operations. They default to utilizing half the number of threads available and that seems be a reliable amount for fast execution.

**Comment by bkamins** [comment]
> I believe GPU support could be orthogonal to anything directly in the DataFrames.jl library

This is true. What I say is that we are not going to implement GPU specific algorithms in DataFrames.jl for now.

> I've tested out some of the operations from the H2O benchmark and I'm seeing similar timings for first and second runs.

This is unrelated to number of cores used I think.

> Does DataFrames enable parallelism under the hood

Yes (assuming you are testing `main`, which you should)

> is there a way to set the number of cores (or threads) before running the code?

Yes, just start Julia with the number of cores you want

> I have found that settings the number of threads to the max amount with data.table tends to slow down the operations.

This is a correct observation in general.

> They default to utilizing half the number of threads available and that seems be a reliable amount for fast execution.

This is because on most machines you have twice as many logical cores as physical cores, but this behavior may vary depending on what hardware you are running your tests.

For now in H2O benchmarks we have opted to use all logical cores in the tests, but we might cut it down to half if it turns out that this would be better.

**Comment by AdrianAntico** [comment]
@bkamins thanks for your responses. Unrelated question - are there plans to incorporate windowing functions, such as lag, moving average, etc. by groups?

**Comment by bkamins** [comment]
These functionalities should be provided by third party packages and they just should work. E.g. use ShiftedArrays.jl, RollingFunctions.jl or DSP.jl.

**Comment by ViralBShah** [comment]
This would have been a good thing for a GSOC project.

**Comment by ViralBShah** [comment]
Working with the `neuro` datset from RDatasets, I could not convert a vector with missing data into a CuArray:

```
julia> cu(neuro.V1)
ERROR: CuArray does not yet support union bits types
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] CuArray{Union{Missing, Float64}, 1}(#unused#::UndefInitializer, dims::Tuple{Int64})
    @ CUDA ~/.julia/packages/CUDA/Zmd60/src/array.jl:18
  [3] (CuArray{Union{Missing, Float64}, N} where N)(#unused#::UndefInitializer, dims::Tuple{Int64})
```

**Comment by bkamins** [comment]
Yes, but this is an issue that is unrelated to DataFrames.jl.

**Comment by ViralBShah** [comment]
That's right - I will need to find the right place to file in the GPU ecosystem. I  just thought I would add it in here since there's an ongoing discussion.
