### ISSUE TITLE
Make PrettyTables.jl 1.0 as a dependency

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#2714]
Before 1.0 release of DataFrames.jl we need PrettyTables.jl 1.0 as a dependency.

**Comment by ronisbr** [comment]
I just tag v1.0.0 :)

https://github.com/JuliaRegistries/General/pull/34808

**Comment by bkamins** [comment]
Thank you!

**Comment by nathanrboyer** [comment]
Question: Does this change how I should be using DataFrames.jl and PrettyTables.jl together? Do I still need to `using` both packages? Should I still call `pretty_table(df, ...)` to display my DataFrames, or is there a function within DataFrames.jl that I should be using now?

**Comment by ronisbr** [comment]
You can choose. PrettyTables is loaded when you load DataFrames. Thus, `using PrettyTables` will just export the symbols to you.

If you call `show(df; kwargs...)`, then you can pass any keyword directly to PrettyTables.jl. The only problem is if you want a complete different customization of how a DataFrame is printed. In this case, it is better to call `pretty_table` directly.

**Comment by nathanrboyer** [comment]
>Thus, using PrettyTables will just export the symbols to you.

I'm not sure what you mean by "symbols".

>If you call show(df; kwargs...), then you can pass any keyword directly to PrettyTables.jl.

It seems to not really be the same.
```
julia> using DataFrames, PrettyTables

julia> df = DataFrame(x=['a','b','c'], y=1.0:3.0)
3×2 DataFrame
 Row │ x     y       
     │ Char  Float64 
─────┼───────────────
   1 │ a         1.0
   2 │ b         2.0
   3 │ c         3.0

julia> pretty_table(df, nosubheader=true, title="Title", title_alignment=:c, title_same_width_as_table = true, tf=tf_unicode_rounded)
   Title
╭───┬─────╮
│ x │   y │
├───┼─────┤
│ a │ 1.0 │
│ b │ 2.0 │
│ c │ 3.0 │
╰───┴─────╯

julia> show(df, nosubheader=true, title="Title", title_alignment=:c, title_same_width_as_table = true, tf=tf_unicode_rounded)
    Title
 Row │ x  y   
─────┼────────
   1 │ a  1.0
   2 │ b  2.0
   3 │ c  3.0
```
> PrettyTables is used as print back-end of DataFrames for text.

I am trying to understand the implications of that. Can I configure default keyword arguments somehow so that below will appear like the `pretty_table` command above?
```
julia> df
3×2 DataFrame
 Row │ x     y       
     │ Char  Float64 
─────┼───────────────
   1 │ a         1.0
   2 │ b         2.0
   3 │ c         3.0
```

**Comment by ronisbr** [comment]
Hi @nathanrboyer 

> I'm not sure what you mean by "symbols".

When loading DataFrames, PrettyTables is loaded. However, you cannot call `pretty_table` because the functions are now exported to you. When you type `using PrettyTables`, then you have access to those symbols (functions, variables, etc.). There is no additional loading whatsoever.

> It seems to not really be the same.

PrettyTables is the printing backend for DataFrames. However, DataFrames add a lot of configurations on top of it. You can check it here: https://github.com/JuliaData/DataFrames.jl/blob/7fcb93baf95b985f1ca4a691eb066c7f5f72b3f4/src/abstractdataframe/show.jl#L259

You can customize an additional option (or override one of them) by passing the keywords to `show`, like, for example `show(df, nosubheader=true)`. Notice that this will add the option `nosubheader=true` to those already configured in DataFrames.

> I am trying to understand the implications of that. Can I configure default keyword arguments somehow so that below will appear like the `pretty_table` command above?

You can always create a configuration dictionary using `set_pt_conf` and call it with `pretty_table_with_conf`. In this case, you need to copy all the configurations inside DataFrames.
