### ISSUE TITLE
`dropmissing!` creates weird memory bugs/errors on 1.7 and 1.6

### ISSUE THREAD

**Issue by pcjentsch** [JuliaData/DataFrames.jl#2819]
The MWE is available in [this repository](https://github.com/pcjentsch/DataFramesMWE). It uses the publicly available Our World in Data COVID dataset. Let me know if this should be posted in the Julia language repository instead. I am using the latest DataFrames release.

This code creates a few different error messages.

On 1.7
```
corrupted double-linked list

```
another message
```
julia: malloc.c:4259: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
```

(then hangs)

On 1.6
```
julia-1.6: malloc.c:4259: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.

signal (6): Aborted
in expression starting at /home/peterj/scratch.jl:45
```

Generally replacing the line
```
      dropmissing!(location_subset, [:new_cases_smoothed,:new_vaccinations_smoothed,:total_cases])
```
with
```
 location_subset =dropmissing(location_subset, [:new_cases_smoothed,:new_vaccinations_smoothed,:total_cases])
```
avoids this error.

**Comment by bkamins** [comment]
I have traced the source of the bug. Unfortunately it seems to be in Julia Base (which is unlikely), so this is strange.

The problem happens if rows that need to be removed from `location_subset` form a continuous block. In this case Julia Base calls a fast method for `deleteat!` (which takes a starting position and number of elements to remove). For some strange reason this sometimes fails.

The problem is fixed when in line https://github.com/JuliaData/DataFrames.jl/blob/ab5ffd7946577b8542caf60963df33a9fe11bba2/src/dataframe/dataframe.jl#L978 we write instead:
```
drop = collect(_findall(inds))
```
(this forces Julia Base to use another internal implementation of `deleteat!`).

I will try asking Julia core devs for help.

**Comment by bkamins** [comment]
@pcjentsch - if you can/have time can you please test the code with the fix in https://github.com/JuliaLang/julia/pull/41646 (if not I can do it later, but currently I do not have access to an appropriate machine to do this). Thank you!

Nevertheless I will add a fix to DataFrames.jl code and make a patch release.

Thank you for reporting.

**Comment by bkamins** [comment]
@pcjentsch - please update DataFrames.jl to 1.2.1 release and all will work OK.

**Comment by pcjentsch** [comment]
Great, thank you! I will not have time to test the new Julia branch for the next week or so but I appreciate your fast response time.
