### ISSUE TITLE
Performance Issues with filter and subset 

### ISSUE THREAD

**Issue by storopoli** [JuliaData/DataFrames.jl#2821]
I get different allocations and timings when filtering rows with `filter` or `subset`.

Here is a MWE.

Setup:

```julia
julia> using DataFrames, Random, BenchmarkTools
julia> Random.seed!(123);
julia> N = 10^6;
julia> df = DataFrame(a=rand(["A", "B", "C"], N), b=rand(["X", "Y", "Z"], N));
julia> f(a, b) = a == "A" && b == "X";
```

Benchmarks:

```julia
julia> @btime filter([:a, :b] => f, df);
  10.888 ms (33 allocations: 2.67 MiB)

julia> @btime subset(df, [:a, :b] => ByRow(f));
  10.688 ms (179 allocations: 3.64 MiB)

julia> @btime filter([:a, :b] => f, df);
  10.874 ms (33 allocations: 2.67 MiB)

julia> @btime subset(df, [:a, :b] => ByRow(f));
  10.677 ms (179 allocations: 3.64 MiB)
```

Comparing with `getindex` on vector of `Bool` as row selector:

```julia
julia> idxs = f.(df.a, df.b);

julia> @btime df[idxs, :];
  595.542 μs (19 allocations: 2.55 MiB)
```

Enviroment Mac M1 on Rosetta:
```julia
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, westmere)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_NUM_PRECOMPILE_TASKS = 4
  JULIA_GR_PROVIDER = GR

(@v1.6) pkg> st DataFrames
      Status `~/.julia/environments/v1.6/Project.toml`
  [a93c6f00] DataFrames v1.2.1
```

**Comment by bkamins** [comment]
The way to do the benchmarks is:
```
julia> @btime filter([:a, :b] => f, $df);
  13.442 ms (31 allocations: 2.67 MiB)

julia> @btime subset($df, [:a, :b] => ByRow(f));
  13.283 ms (178 allocations: 3.64 MiB)

julia> @btime $df[f.($df.a, $df.b), :];
  13.704 ms (26 allocations: 2.67 MiB)

julia> @btime subset($df, :a => ByRow(==("A")), :b => ByRow(==("X")));
  17.985 ms (248 allocations: 4.59 MiB)
```

Conclusions:
1. First `subset` allocates more as it invokes the `select` machinery under the hood and handles things like `skipmissing` kwarg (but as you can see, and as @pdeffebach commented just copying memory is super fast so the overhead negligible);
2. `getindex` is just as fast as `filter` and roughly does the same number of significant allocations;
3. Second `subset` is slower because it has to create 2 filtering vectors, and then combine hem into one final vector that is used to do the final filtering (so it does more work; this is unavoidable).

I am closing this as I think everything here works as expected, but if you have any questions please comment.

**Comment by storopoli** [comment]
Crystal clear. Thanks!
