### ISSUE TITLE
implement `Tables.materializer(::Type{<:AbstractDataFrame})`?

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaData/DataFrames.jl#2833]
The `Tables.materializer` function spec is unclear; the docs suggest that it should accept a *value* and return a function to materialize a generic table to a different value of the same type, which are the methods implemented in DataFrames.  But it would also be useful to be able to get the materializer given the *type*.  That's straightforward for DataFrames:

```julia
Tables.materializer(::Type{<:AbstractDataFrame}) = DataFrame
```

The only uncertainty is whether this is something that should work for all tables (if not, it's not particularly useful to implement here), so this is more of a Tables.jl issue: https://github.com/JuliaData/Tables.jl/issues/246

**Comment by pdeffebach** [comment]
I don't think any Tables.jl stuff works on types, right? Just instances?

**Comment by kleinschmidt** [comment]
```julia
julia> using Tables, DataFrames

julia> Tables.istable(DataFrame)
true
```

**Comment by pdeffebach** [comment]
That's interesting, because the Tables.jl docs don't mention that at all. It doesn't seem to be a requirement for the interface.

**Comment by bkamins** [comment]
@quinnj - can you please recommend a decision? Thank you!

**Comment by kleinschmidt** [comment]
> That's interesting, because the Tables.jl docs don't mention that at all. It doesn't seem to be a requirement for the interface.

It's actually not clear what the `table` in the (ahem) table of interface functions refers to.  For instance, the brief description for `istable(table)` reads "Declare that your table type implements the interface", which suggests that `table` is (or could be) a Type.  In fact, most of the descriptions of those functions refer to "your table type".

**Comment by krynju** [comment]
Current Tables.jl docs make sense (although they're little ambigous on this) and the typical usage of materializer is fine with it only taking a table instance as an arg.

Adjusted example from TableOperations.jl:
```
ctable = (A=[1, missing, 3], B=[1.0, 2.0, 3.0], C=["hey", "there", "sailor"])

table_subset = ctable |> TableOperations.select(:C, :A) |> Tables.materializer(ctable)
```

I raised this here https://github.com/JuliaData/Tables.jl/issues/246 some time ago, because I think this is more of a topic for all Tables compatible sources, since only having DataFrames implement it is not useful overall.

My use case starts with asking the user what table type they want to use, then converting the user provided source to that tabletype. For that I need to call `Tables.materializer(tabletype())(source)` which assumes tabletype has a no-arg constructor (which is not ideal, because it might not have one).

**Comment by quinnj** [comment]
Sorry for the slow response here; I thought it was mentioned in the Tables.jl docs, but I can't seem to find it now, so maybe it got removed at some point. But in general for Tables.jl interface functions, if you can define a "trait" interface function on your _type_, then you should define it on the _type_ since that plays nicely with compiler optimizations. There might be cases, like a generic table-wrapper, where it might not be possible to define `Tables.istable` or `Tables.materializer` on the _type_, but only on an _instance_. This is fine as well.

For _consumers_ of the interface functions, however, they should _always_ call the interface functions on _instances_. In almost all cases, we have a fallback definition already defined like `Tables.istable(x::T) where {T} = Tables.istable(T)`.

I'll try to find a good spot in the docs to clarify this, but I hope that helps in this discussion.

**Comment by bkamins** [comment]
OK - so this means we should implement the `Tables.materializer` on types in DataFrames.jl. I have opened #2839 that does that.

@quinnj - could you please review

@kleinschmidt - could you please check if this resolves your issue?

---

A side note:

@pdeffebach - this is a kind of issues that additionally strengthens the fact that we have only `DataFrame` and `SubDataFrame` as instances of `AbstractDataFrame`. I have no problem with this as you know, but later, if people would implement a custom `AbstractDataFrame` subtype (as sometimes people ask to) then they would have to carefully think how they want to handle `Tables.materializer` for their type (and also for row and column iterators of their type).

These are considerations why I say that while it is possible I would not advise creating new `AbstractDataFrame` subtypes - it is just too very to make sure all works as expected, as we have too much functionality built around `AbstractDataFrame`.
