### ISSUE TITLE
Want to contribute to DataFrames.jl

### ISSUE THREAD

**Issue by xluo127** [JuliaData/DataFrames.jl#2879]
Hi! It is my first time opening a PR. I am interested in contributing to DataFrames.jl. I opened a draft PR: #2877. 

I want to get help from you so that I can try to do some contributions. The issue I am focusing on so far is #2747.

I have reviewed the contributing guidelines, but there might still be something wrong. If the draft PR has to be closed or something else I have to do before hearing from you, please let me know, thanks!

**Comment by bkamins** [comment]
Thank you for contributing. You can assume that anything you do in this repository will receive an answer, normally within one business day. Regarding the issue at hand - I have commented in the PR.

Decisions what to do in such cases are quite hard and usually take a lot of discussion because it is important to minimize the number of things that users need to learn.

**Comment by xluo127** [comment]
OK, thank you!
