### ISSUE TITLE
Trimming variables in a data frame

### ISSUE THREAD

**Issue by jo-fleck** [JuliaData/DataFrames.jl#2891]
Many thanks for everyone's work on DataFrames.jl !

In empirical work, it's often useful to remove outliers by deleting x% of bottom and top values. Is there a way to do this for columns in a data frame? 

If there isn't and you find it a useful enhancement:

- [StatsBase.jl](https://juliastats.org/StatsBase.jl/latest/robust/#Robust-Statistics-1) has `trim` and `trim!` but I haven't found an easy way to use them when working with data frames. (For example, it only works on one column at a time so I ended up with data frames of different lengths.)
- I wrote a simple function which could give some inspiration what kind of API might be useful:
```
function trim_df!(df, v, pc) # removes bottom and top pc%
    vars_pc_lower_value = percentile(df[:, v], pc)
    vars_pc_upper_value = percentile(df[:, v], 100-pc)
    filter!(r -> (r[v] .>= vars_pc_lower_value && r[v] .< vars_pc_upper_value), df);
end
```

**Comment by bkamins** [comment]
Thank you for the proposal.

The design policy of JuliaData ecosystem is that in DataFrames.jl we only keep:
1. essential low-level functions for working with data frames
2. optionally we extend selected functions defined in Julia Base for working with DataFrames.jl

Unfortunately, I have to reject your proposal as it does not meet any of these conditions. The function is too specific - and per your example - it is easy enough to implement it in a few lines. Normally such functions are recommended to be added to utility packages that are built on top of DataFrames.jl (like e.g. DataFramesMeta.jl does - but it has a bit different scope - concentrating on providing a nicer syntax).

As an implementation note:
* in order to make it a package-quality function you would need to decide how to handle `missing` values (indeed `trim` does not handle missings currently either - it was probably implemented before `missing` was a defined interface)
* your implementation is inconsistent with `trim` in StatsBase.jl (e.g. in how it handles ties) - so it would have to be decided which behavior you prefer (this is even after correcting for differences in proposed API)
* your implementation would be faster if you have written it as follows:
```
function trim_df!(df, v, pc) # removes bottom and top pc%
    vars_pc_lower_value = percentile(df[!, v], pc)
    vars_pc_upper_value = percentile(df[!, v], 100-pc)
    filter!(v => x -> vars_pc_lower_value < x < vars_pc_upper_value), df)
    return df
end
```

---

To give you some rationale behind such policy:
1. DataFrames.jl already is one of the biggest packages in the ecosystem in terms of both complexity and provided functionality. We need to ensure that what we provide in the package is well tested and well maintained.
2. Number of potential functions that could be built on top of `DataFrame` object is countless so we have to put some cutoff on what is included (notice that e.g. we even do not provide CSV reading and writing as a part of the package or that we delegate printing data frames to PrettyTables.jl; in the very deep past even things like https://github.com/JuliaStats/StatsModels.jl were a part of this package but they were stripped from it as the ecosystem grew)

Thank you for using the package!

**Comment by jo-fleck** [comment]
Many thanks @bkamins for looking into this and your comprehensive explanation + feedback!
