### ISSUE TITLE
subset doesn't accept a vector of transformations

### ISSUE THREAD

**Issue by knuesel** [JuliaData/DataFrames.jl#2924]
It seems inconsistent that `subset` won't accept a vector of transformations, like `select`, etc.

This came up while writing an answer to [this](https://discourse.julialang.org/t/dataframe-filtering-based-on-conditions-comparing-one-column-to-other-columns/70802) Discourse thread: I was surprised to find that the following doesn't work:

```julia
df = DataFrame(rand(8,5), :auto)
columns = names(df, Not(Between(:x3, ncol(df))))

# This triggers an ArgumentError:
subset(df, vcat.(columns, "x5") .=> .<)
```

so I need instead to write `subset(df, (vcat.(columns, "x5") .=> .<)...)`.

**Comment by bkamins** [comment]
It was intentional - to avoid complicating the things too much and the intention was to require using `...`.
It can be easily added though.
(this is the usual @nalimilan brand - "if you are unsure make it an error so that later you can decide whatever you prefer")

@nalimilan - do you have any opinion here?

**Comment by nalimilan** [comment]
Sure!

**Comment by bkamins** [comment]
@knuesel - please see https://github.com/JuliaData/DataFrames.jl/pull/2926 if it fixes your issues.

**Comment by knuesel** [comment]
@bkamins yes that fixes it, thanks!
