### ISSUE TITLE
DataFrames errors on loading with `--depwarn=error`

### ISSUE THREAD

**Issue by KristofferC** [JuliaData/DataFrames.jl#2935]
```jl
ERROR: LoadError: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
Stacktrace:
  [1] UnionAll(v::TypeVar, t::Any)
    @ Core ./boot.jl:255
  [2] precompile(all::Bool)
    @ DataFrames ~/.julia/packages/DataFrames/vuMM8/src/other/precompile.jl:65
  [3] precompile()
    @ DataFrames ~/.julia/packages/DataFrames/vuMM8/src/other/precompile.jl:19
...
```

**Comment by bkamins** [comment]
I know about it, but have not decided how this should be handled. This is tracked in cryptic https://github.com/JuliaData/DataFrames.jl/issues/2921 😄.

The issue is that the warnings are triggered by statements generated by [SnoopCompile.jl](https://github.com/timholy/SnoopCompile.jl) under Julia 1.6 and if you use Julia nightly there are these warnings produced.

That is why I am waiting with DataFrames.jl 1.3 release for Julia 1.7 release to be sure that we are in sync with at least the latest released version.

There are the following considerations here:
* I could explicitly try to disable producing warnings in the part of the code that calls precompilation; do you know if this is possible (I have not dug into this yet);
* I could generate separate precompile statements for different Julia versions (I really would prefer to avoid doing this as this is nasty);
* I hope that precompile statements generated under Julia 1.7 (when I re-generate them) would work on earlier Julia versions without warnings (I am waiting for Julia 1.7 release to check this);
* finally I could enable precompilation only on Julia version under which DataFrames.jl was released (i.e. after 1.7 release precompilation would happen only on Julia 1.7).

These are current ideas. I have not worked on it yet as I am waiting for Julia 1.7 release to test them. But if there are general recommendations how SnoopCompile.jl should be used to avoid producing warnings I would love to hear them before I start working on this.

CC @nalimilan @timholy

**Comment by timholy** [comment]
Easiest workaround is to precompile by "doing work" rather than "calling `precompile`". In other words, just take whatever script you used to generate the precompiles, and instead run it when the package is being built. See ImageCore.jl for an example.

**Comment by bkamins** [comment]
Interesting - this is roughly what I did in DataFrames.jl 1.3.0 release last week, see https://github.com/JuliaData/DataFrames.jl/blob/12c586c07f4e33ceff62504e3a68bd8c7c2c9776/src/other/precompile.jl#L96 (actually I used a mixed approach, but it seems this is also what ImageCore.jl does).

Thank you for commenting.
