### ISSUE TITLE
Keyword arg `cols` and `source` for `mapreduce`

### ISSUE THREAD

**Issue by haberdashPI** [JuliaData/DataFrames.jl#3028]
Just learned that `reduce` has support for `cols` and `source` when called with `vcat`. However, `mapreduce` does not. Would be nice to have it!

**Comment by bkamins** [comment]
Unfortunately it is impossible to have it in general see https://github.com/JuliaData/DataFrames.jl/issues/3016.
The reason is that your source data would have to be data frames and you would have to ensure that the map part of the `mapreduce` also returns data frames, which cannot be checked in general.

So I am closing this request (but if you have some idea how to resolve the issues mentioned in https://github.com/JuliaData/DataFrames.jl/issues/3016 please comment and I will re-open)
