### ISSUE TITLE
Add `fillmissing` 

### ISSUE THREAD

**Issue by lfenzo** [JuliaData/DataFrames.jl#3041]
Is it reasonable to think of a `fillmissing` function for DataFrames.jl? I was planning on implementing it with the following methods:

```julia
fillmissing(df::AbstractDataFrame, value)
fillmissing(df::AbstractDataFrame, cols, values)
fillmissing(df::AbstractDataFrame, pairs...)
```

(as well as the `!` variants) but I wanted to validate this first before coding anything.

In context, the usage should be something like:

```julia
fillmissing(df, [:some_col, :other_col], [0.5, 1.2]
```
and

```julia
fillmissing(df, :some_col => 0.5, :other_col => 1.2)
```

**Comment by bkamins** [comment]
How different it would be to this in declarative style:
```
transform(df, :some_col => ByRow(x -> coalesce(x, 0.5)), renamecols=false)
```
?
or e.g. in place in imperative style
```
df.somecol = coalesce.(df.somecol, 0.5)
```

**Comment by lfenzo** [comment]
Hello @bkamins 

> How different it would be to this in declarative style (...) or e.g. in place in imperative style

To be honest, I wasn't aware of these approaches, thanks for pointing them out! I this case they would perform the same operation as `fillmissing`.

The point of having this `fillmissing` function -- which would follow up already existing functions like `dropmissing`, `allowmissing` and `disallowmissing` -- would be to provide a simpler and more expressive approach to `missing` imputation as

```julia
fillmissing(df, :some_col => 0.5)
```
seems to me simpler than

```julia
transform(df, :some_col => ByRow(x -> coalesce(x, 0.5)), renamecols=false)
```

The matter of simplicity is, in fact, rather subjective, but unless there are performance compromises I think that keeping these operations as simple as possible is always better.

What do you think?

**Comment by bkamins** [comment]
I can see the merit of consistency with other `*missing` functions. I also agree that making it convenient to handle `missing` values makes sense.

Another option would be to add methods to `coalesce` (to reuse existing function) like:
```
coalesce(df, :some_col => 0.5, :other_col => 1.2) # new data frame returned
coalesce!(df, :some_col => 0.5, :other_col => 1.2) # in place variant
```

@nalimilan - what do you think?

**Comment by nalimilan** [comment]
Another syntax that already works is `transform(df, :some_col => (x -> replace(x, missing => 0.5)), renamecols=false)`, which could become `transform(df, :some_col => replace(_, missing => 0.5), renamecols=false)` if https://github.com/JuliaLang/julia/pull/24990 ends up being merged in Julia at some point. 

One of the design principles we have followed in DataFrames.jl is to keep the API simple, with few generic functions that allow doing everything one needs. That said, this is always a trade-off between simplicity and convenience and there's no clear rule to decide where to draw the line. For example, `dropmissing` isn't strictly necessary either as the same result can be achieved with `subset`. The question boils down to how frequent to we expect this operation to be, as we cannot add special functions for every possible operation users may perform. In what kind of situation does this kind of need arise? Often, the value you want to replace `missing` with depends on some calculation performed on the column so you need something more complex anyway.

FWIW, Impute.jl [has a function](https://invenia.github.io/Impute.jl/stable/api/imputation/#Impute.replace) to replace missing values with a specified value. Their current API allows passing values of various types so that the one with the type corresponding to each column is chosen automatically. It would make sense to allow passing a vector of `col => value` pairs too.

If we add something like this, I'd tend to prefer a function called `fillmissing` or `replacemissing` than overloading `coalesce`, as the API of the latter is quite different (all arguments have the same "role" there).

See also semi-related discussion about `replace(df, ...)` at https://github.com/JuliaData/DataFrames.jl/issues/2257.

**Comment by bkamins** [comment]
> The question boils down to how frequent to we expect this operation to be, as we cannot add special functions for every possible operation users may perform.

Yes, this is a key question. Especially in relation to #2257, which is more general but tries to do the same.

I feel that we could add one convenience function for these kind of operations as, in general, recoding, is a quite common operation. But the question is what API would be flexible enough and yet not overly complicated.

**Comment by lfenzo** [comment]
After thinking a little longer about this matter, I've come to the conclusion that, in my point of view, Impute.jl already provides this functionality with the proper trade-off between ease of use and generalization for this task.

In this sense, even though DataFrames.jl provides some `*missing` functions (which, as far as I know, are the "glue" between the two packages), `fillmissing` would only provide unnecessarily overlapping functionalities across DataFrames.jl and Impute.jl,

**Comment by bkamins** [comment]
OK - so I am closing this issue. However, if anyone feels it should be re-opened please comment.
