### ISSUE TITLE
UndefRefError: access to undefined reference

### ISSUE THREAD

**Issue by cadoubs** [JuliaData/DataFrames.jl#3053]
UndefRefError when accessing an #undef element on DataFrames v1.3.4, Julia 1.7.2
```
julia> df = DataFrame([:A 1; :B 2],[:A,:B])
2×2 DataFrame
 Row │ A    B   
     │ Any  Any 
─────┼──────────
   1 │ A    1
   2 │ B    2

julia> dfs = similar(df,1)
1×2 DataFrame
 Row │ A       B      
     │ Any     Any    
─────┼────────────────
   1 │ #undef  #undef 

julia> dfs[1,:A]
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex(A::Vector{Any}, i1::Int64)
   @ Base .\array.jl:861
 [2] getindex(df::DataFrame, row_ind::Int64, col_ind::Symbol)
   @ DataFrames C:\Users\Fabien\.julia\packages\DataFrames\MA4YO\src\dataframe\dataframe.jl:494
 [3] top-level scope
   @ REPL[183]:1
```

Side remark : why df columns types are Any ?
```
julia> df = DataFrame(A=[:A,:B],B=[1,2])
2×2 DataFrame
 Row │ A       B
     │ Symbol  Int64
─────┼───────────────
   1 │ A           1
   2 │ B           2

julia> dfs = similar(df,1)
1×2 DataFrame
 Row │ A       B
     │ Symbol  Int64
─────┼────────────────────
   1 │ #undef  1148127392

julia> dfs[1,:A]
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex(A::Vector{Symbol}, i1::Int64)
   @ Base .\array.jl:861
 [2] getindex(df::DataFrame, row_ind::Int64, col_ind::Symbol)
   @ DataFrames C:\Users\Fabien\.julia\packages\DataFrames\zqFGs\src\dataframe\dataframe.jl:494
 [3] top-level scope
   @ REPL[17]:1
``` 

Strangely no errors in the following case :
```
julia> dfs = DataFrame(A = [ undef])
1×1 DataFrame
 Row │ A
     │ UndefIni… 
─────┼───────────
   1 │ #undef

julia> dfs[1,:A]
UndefInitializer(): array initializer with undefined values
```

Probably an initialization issue that has nothing to do with Any type
```
julia> df = DataFrame(A=[undef, 1],B=[undef,2])
2×2 DataFrame
 Row │ A       B
     │ Any     Any
─────┼────────────────
   1 │ #undef  #undef
   2 │ 1       2

julia> delete!(df,2)
1×2 DataFrame
 Row │ A       B
     │ Any     Any
─────┼────────────────
   1 │ #undef  #undef

julia> df[1,:A]
UndefInitializer(): array initializer with undefined values
```

**Comment by bkamins** [comment]
All this behavior is correct. The issue is that PrettyTables.jl does incorrect printing of `undef`, see https://github.com/ronisbr/PrettyTables.jl/issues/170.

To answer your questions:

> UndefRefError when accessing an #undef element

This is a general rule in Julia that accessing `#undef` is an error, eg.
```
julia> x = Vector{String}(undef, 1)
1-element Vector{String}:
 #undef

julia> x[1]
ERROR: UndefRefError: access to undefined reference
```

> why df columns types are Any ?

Because your source `Matrix` has `Any` element type:
```
julia> [:A 1; :B 2]
2×2 Matrix{Any}:
 :A  1
 :B  2
```

> Strangely no errors in the following case :

The reason is that `[undef]` creates a 1-element vector with a valid entry:
```
julia> [undef]
1-element Vector{UndefInitializer}:
 UndefInitializer(): array initializer with undefined values
```
you probably meant:
```
julia> Vector{Any}(undef, 1)
1-element Vector{Any}:
 #undef
```
which is a way to define a 1-element vector with undefined contents.

CC @ronisbr

**Comment by cadoubs** [comment]
Thank you for your reply. It is clear now.

Regarding DataFrame construction, shouldn't be `DataFrame([:A 1,:B 2],[:c1,:c2])` equivalent to `DataFrame(c1=[:A,:B], c2=[1,2])`?

```
julia> DataFrame([:A 1;:B 2],[:c1,:c2])
2×2 DataFrame
 Row │ c1   c2
     │ Any  Any
─────┼──────────
   1 │ A    1
   2 │ B    2

julia> DataFrame(c1=[:A,:B], c2=[1,2])
2×2 DataFrame
 Row │ c1      c2
     │ Symbol  Int64
─────┼───────────────
   1 │ A           1
   2 │ B           2
```

**Comment by bkamins** [comment]
> Regarding DataFrame construction, shouldn't be DataFrame([:A 1,:B 2],[:c1,:c2]) equivalent for column types to DataFrame(c1=[:A,:B], c2=[1,2])?

No it should not. The reason is that we should respect `eltype` of source container as later user might want to assign values to columns that are of the original type (if we restricted the `eltype` later user would get an error - imagine e.g. you passed a `Matrix` with 0-rows in this case you would not even have values to perform the operation you ask for). However, it is easy to restrict `eltype` of columns of a data frame if you want it:
```
julia> identity.(DataFrame([:A 1;:B 2],[:c1,:c2]))
2×2 DataFrame
 Row │ c1      c2
     │ Symbol  Int64
─────┼───────────────
   1 │ A           1
   2 │ B           2
```

**Comment by cadoubs** [comment]
OK, it is clear and logical. Thank you for the `identity` trick !
