### ISSUE TITLE
DataFrame from Matrix with Error when not specifying `:auto`

### ISSUE THREAD

**Issue by lfenzo** [JuliaData/DataFrames.jl#3090]
It occurs to me that using `:auto` should be the default behavior when column names are not specified, however I don't know if this impacts the consistency between the other `DataFrame` constructors.

```
ERROR: LoadError: ArgumentError: `DataFrame` constructor from a `Matrix` requires passing :auto as a second argument to automatically generate column names: `DataFrame(matrix, :auto)`
Stacktrace:
 [1] DataFrame(matrix::Matrix{Float32})
   @ DataFrames ~/.julia/packages/DataFrames/zqFGs/src/dataframe/dataframe.jl:381
 [2] main()
   @ Main ~/Documents/projetos/dl-solar-sao-paulo/src/train_model.jl:115
 [3] top-level scope
   @ ~/Documents/projetos/dl-solar-sao-paulo/src/train_model.jl:132
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [5] top-level scope
   @ REPL[5]:1
 [6] top-level scope
   @ ~/.julia/packages/CUDA/tTK8Y/src/initialization.jl:52

```

**Comment by bkamins** [comment]
`DataFrame` constructor with a single positional argument is reserved for Tables.jl integration.
The second positional argument `:auto` is needed to signal that the user wants to opt-out from calling Tables.jl mechanism. And Tables.jl does not consider `Matrix` to be a table. Alternatively you could write:
```
DataFrame(Tables.table(some_matrix))
```

Now, you might ask why? The reason is that most likely you feel that columns of a matrix should be columns of a data frame (and this is what `:auto` ensures). However, there are some non-standard matrices that want to be recognized as tables in a different way (this is not a hypothetical discussion - there actually are such matrix types present - e.g. in differential equations ecosystem).
