### ISSUE TITLE
[Problem] about filter and dropmissing usage

### ISSUE THREAD

**Issue by nesteiner** [JuliaData/DataFrames.jl#3105]
here is a dataframe with missing value
```julia
df = DataFrame(x = [1, missing, 2])
```
and when you call filter to drop missing value
```julia
df2 = filter(row -> !ismissing(row.x), df)
```
the result is 
![image](https://user-images.githubusercontent.com/46296608/180922960-9b06452a-99c1-4433-a26a-adf52f10e64f.png)
the x column eltype contains Missing still

but when calling dropmissing to drop missing value
```julia
df3 = dropmissing(df)
```

the result is 
![image](https://user-images.githubusercontent.com/46296608/180923121-2362987d-eefd-425c-925f-c643b2d04a08.png)

so what's the problem with `filter` ?

**Comment by bkamins** [comment]
There is no problem with `filter`.

`filter` only removes values from the collection, but does not change its element type. To understand why it makes sense consider the following `filter`:
```
julia> using DataFrames

julia> df = DataFrame(a=1)
1×1 DataFrame
 Row │ a
     │ Int64
─────┼───────
   1 │     1

julia> df2 = filter(row -> false, df)
0×1 DataFrame

julia> df2.a
Int64[]

julia> typeof(df2.a)
Vector{Int64} (alias for Array{Int64, 1})
```
I assume you agree that in this case element type of `df2.a` should be `Int64` and not `Union{}` (since it has no elements so `Union{}` is eltype that would be obtained if we applied type narrowing).

As `dropmissing` is a more specialized function we know that we can change the element type of the collection. Note, that, in fact it is only an opt-in. You can decide if you want to perform narrowing of eltype using the `disallowmissing` keyword argument.

**Comment by bkamins** [comment]
There is no problem with `filter`.

`filter` only removes values from the collection, but does not change its element type. To understand why it makes sense consider the following `filter`:
```
julia> using DataFrames

julia> df = DataFrame(a=1)
1×1 DataFrame
 Row │ a
     │ Int64
─────┼───────
   1 │     1

julia> df2 = filter(row -> false, df)
0×1 DataFrame

julia> df2.a
Int64[]

julia> typeof(df2.a)
Vector{Int64} (alias for Array{Int64, 1})
```
I assume you agree that in this case element type of `df2.a` should be `Int64` and not `Union{}` (since it has no elements so `Union{}` is eltype that would be obtained if we applied type narrowing).

As `dropmissing` is a more specialized function we know that we can change the element type of the collection. Note, that, in fact it is only an opt-in. You can decide if you want to perform narrowing of eltype using the `disallowmissing` keyword argument.
