### ISSUE TITLE
Add references to `names` documentation

### ISSUE THREAD

**Issue by quinnj** [JuliaData/DataFrames.jl#3171]
I wanted to brush up on the various "selection" options for a DataFrame. I conveniently found a section about the `names` function in the "Getting Started" page of the manual/docs. And clicking into the reference docs for `names` provided a fair amount of details, particularly with some good examples of using function selectors. But I felt a bit lots with:
```
any column selector (Symbol, string or integer; :, Cols, All, Between, Not, a regular expression, or a vector of Symbols, strings or integers)
```
i.e. it wasn't clear to me what `Cols` or `All` are, and how to use them. And no `(@ref)` links to follow to learn more.

I did eventually find the helpful [Indexing](https://dataframes.juliadata.org/stable/lib/indexing/#Indexing) page which had more information, so maybe the request here is to save the next person some random clicking around and just link to the Indexing page from the `names` docs? Thoughts?

**Comment by bkamins** [comment]
@mortenpi - your advice on Documenter.jl would be welcome here. We have two issues (I ask about MWE, as the rest follows naturally):
* `Cols` is defined in DataAPI.jl, how can we robustly make a cross-reference in a docstring of some function to this definition from DataFrames.jl documentation?
* How can we robustly add a cross-reference in a docstring of some function to some page in the manual? (this is within the same package, DataFrames.jl in this case)

I ask because https://juliadocs.github.io/Documenter.jl/stable/man/guide/#Cross-Referencing describes only cross-referencing within documentation. Thank you!

**Comment by mortenpi** [comment]
Cross-references to other packages must be done by putting the URL in manually unfortunately (https://github.com/JuliaDocs/Documenter.jl/issues/688).

However, to reference a page/section, you should be able to just do `[Section Title](@ref)` as usual, even if the reference is in a docstring (or, in 0.28, you'll be able to even do `[some other text](@ref "Section Title")`; https://github.com/JuliaDocs/Documenter.jl/pull/1900).

**Comment by bkamins** [comment]
OK - I know what to do then. Thank you!
