### ISSUE TITLE
Bool columns are printed as 0/1 in HTML, but not in plain

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataFrames.jl#3265]
Example:
```
julia> df = DataFrame(
           condition = [false, false, true, false, false, false, true, false, false, false],
           time = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
10×2 DataFrame
 Row │ condition  time
     │ Bool       Int64
─────┼──────────────────
   1 │     false      1
   2 │     false      2
   3 │      true      3
   4 │     false      4
   5 │     false      5
   6 │     false      6
   7 │      true      7
   8 │     false      8
   9 │     false      9
  10 │     false     10

julia> PrettyTables.pretty_table(df)
┌───────────┬───────┐
│ condition │  time │
│      Bool │ Int64 │
├───────────┼───────┤
│     false │     1 │
│     false │     2 │
│      true │     3 │
│     false │     4 │
│     false │     5 │
│     false │     6 │
│      true │     7 │
│     false │     8 │
│     false │     9 │
│     false │    10 │
└───────────┴───────┘
```
vs
![image](https://user-images.githubusercontent.com/6187170/210433830-734aa447-bd7c-4704-9eb9-14ebaaf283bc.png)

@ronisbr - I think it is a bug, but can you please confirm?

**Comment by bkamins** [comment]
and
![image](https://user-images.githubusercontent.com/6187170/210434606-80388989-d373-48f3-8787-a31ee5ce8f09.png)

**Comment by ronisbr** [comment]
Hi @bkamins !

I cannot reproduce this bug:

![Captura de Tela 2023-01-03 às 22 40 03](https://user-images.githubusercontent.com/1068295/210468904-e8d3f232-9816-45c6-a0ed-1b45ce2078bf.png)

Furthermore, your display seems wrong. Notice that we added the title "Row" in the row number column, and the text above the `DataFrame` must be `10 x 2 DataFrame` instead of `10 rows x 2 columns`. Can it be an environment problem with old versions of packages?

**Comment by bkamins** [comment]
Right, on 1.4 branch all is good
