### ISSUE TITLE
Feature Request: Allow naming function in `rename` operation pairs.

### ISSUE THREAD

**Issue by nathanrboyer** [JuliaData/DataFrames.jl#3361]
The current options for renaming column(s) with a function are below, but these all require care in dealing with the other columns.
```julia
julia> df = DataFrame(a=1:3, b=4:6, c=7:9)
3×3 DataFrame
 Row │ a      b      c     
     │ Int64  Int64  Int64
─────┼─────────────────────
   1 │     1      4      7
   2 │     2      5      8
   3 │     3      6      9

julia> transform(df, :b => identity => (s -> s * "_new"))
3×4 DataFrame
 Row │ a      b      c      b_new 
     │ Int64  Int64  Int64  Int64
─────┼────────────────────────────
   1 │     1      4      7      4
   2 │     2      5      8      5
   3 │     3      6      9      6

julia> select(df, :a, :b => identity => (s -> s * "_new"), :c)
3×3 DataFrame
 Row │ a      b_new  c     
     │ Int64  Int64  Int64
─────┼─────────────────────
   1 │     1      4      7
   2 │     2      5      8
   3 │     3      6      9
```

I would like the method below added to the `rename` and `rename!` functions, so columns can be renamed in-place with a function just like they can with explicit new name(s).

```julia
julia> rename(df, :b => (s -> s * "_new")) # currently errors
3×3 DataFrame
 Row │ a      b_new  c     
     │ Int64  Int64  Int64
─────┼─────────────────────
   1 │     1      4      7
   2 │     2      5      8
   3 │     3      6      9

julia> rename(df, :b => :b_new)
3×3 DataFrame
 Row │ a      b_new  c     
     │ Int64  Int64  Int64
─────┼─────────────────────
   1 │     1      4      7
   2 │     2      5      8
   3 │     3      6      9
```

It would also work for multiple columns.
```julia
julia> rename(df, 1:2 => (s -> s * "_new"))
3×3 DataFrame
 Row │ a_new  b_new  c     
     │ Int64  Int64  Int64
─────┼─────────────────────
   1 │     1      4      7
   2 │     2      5      8
   3 │     3      6      9
```
There is already a method for applying a function to the entire data frame `rename((s -> s * "_new"), df)`, but I don't think there is currently a way to apply it to only some columns.

**Comment by bkamins** [comment]
The question is if this functionality is needed. Currently instead of:
```
rename(df, 1:2 => (s -> s * "_new"))
```
you should write:
```
rename(df, [n => n * "_new" for n in ["a", "b"])
```
Do you think it is that much less convenient?

And for a common case of:
```
rename(df, :b => (s -> s * "_new"))
```
It is easier to just write:
```
rename(df, :b => "b_new")
```

@nalimilan - what do you think?

**Comment by nathanrboyer** [comment]
None of those options work well if you have a more complicated named function though. Since renaming functions are now available in data frame operations, I think they should also be available in `rename` for consistency.
```julia
julia> df = DataFrame(a=1:3, b=4:6, c=7:9)
3×3 DataFrame
 Row │ a      b      c     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      4      7
   2 │     2      5      8
   3 │     3      6      9

julia> function f(s::Union{String, Symbol})
           s = lpad(s, 3, '_')
           s = rpad(s, 5, '_')
           if contains(s, 'b')
               return uppercase(s)
           else
               return s
           end
       end
f (generic function with 2 methods)

julia> f(:a)
"__a__"

julia> f(:b)
"__B__"

julia> f(:c)
"__c__"

julia> rename(df, :c => f)
ERROR: MethodError: no method matching rename!(::DataFrame, ::Vector{Pair{Symbol, typeof(f)}})

Closest candidates are:
  rename!(::AbstractDataFrame)
   @ DataFrames C:\Users\nboyer.AIP\.julia\packages\DataFrames\58MUJ\src\abstractdataframe\abstractdataframe.jl:248
  rename!(::AbstractDataFrame, ::AbstractVector{Symbol}; makeunique)
   @ DataFrames C:\Users\nboyer.AIP\.julia\packages\DataFrames\58MUJ\src\abstractdataframe\abstractdataframe.jl:199
  rename!(::AbstractDataFrame, ::AbstractVector{<:AbstractString}; makeunique)
   @ DataFrames C:\Users\nboyer.AIP\.julia\packages\DataFrames\58MUJ\src\abstractdataframe\abstractdataframe.jl:207
  ...

Stacktrace:
 [1] rename!(df::DataFrame, args::Pair{Symbol, typeof(f)})
   @ DataFrames C:\Users\nboyer.AIP\.julia\packages\DataFrames\58MUJ\src\abstractdataframe\abstractdataframe.jl:253
 [2] rename(df::DataFrame, args::Pair{Symbol, typeof(f)})
   @ DataFrames C:\Users\nboyer.AIP\.julia\packages\DataFrames\58MUJ\src\abstractdataframe\abstractdataframe.jl:359
 [3] top-level scope
   @ REPL[39]:1

julia> rename(df, [:a, :b] => f)
ERROR: MethodError: no method matching rename!(::DataFrame, ::Vector{Pair{Vector{Symbol}, typeof(f)}})

Closest candidates are:
  rename!(::AbstractDataFrame)
   @ DataFrames C:\Users\nboyer.AIP\.julia\packages\DataFrames\58MUJ\src\abstractdataframe\abstractdataframe.jl:248
  rename!(::AbstractDataFrame, ::AbstractVector{Symbol}; makeunique)
   @ DataFrames C:\Users\nboyer.AIP\.julia\packages\DataFrames\58MUJ\src\abstractdataframe\abstractdataframe.jl:199
  rename!(::AbstractDataFrame, ::AbstractVector{<:AbstractString}; makeunique)
   @ DataFrames C:\Users\nboyer.AIP\.julia\packages\DataFrames\58MUJ\src\abstractdataframe\abstractdataframe.jl:207
  ...

Stacktrace:
 [1] rename!(df::DataFrame, args::Pair{Vector{Symbol}, typeof(f)})
   @ DataFrames C:\Users\nboyer.AIP\.julia\packages\DataFrames\58MUJ\src\abstractdataframe\abstractdataframe.jl:253
 [2] rename(df::DataFrame, args::Pair{Vector{Symbol}, typeof(f)})
   @ DataFrames C:\Users\nboyer.AIP\.julia\packages\DataFrames\58MUJ\src\abstractdataframe\abstractdataframe.jl:359
 [3] top-level scope
   @ REPL[40]:1
```

**Comment by nathanrboyer** [comment]
> you should write:
`rename(df, [n => n * "_new" for n in ["a", "b"]])`
Do you think it is that much less convenient?

That syntax makes sense to me now that you've written it, but I probably wouldn't have come up with it on my own.

The reason for this issue is that I assumed this would work already, and it doesn't. 

```julia
julia> select(df, :a => :d)
3×1 DataFrame
 Row │ d     
     │ Int64
─────┼───────
   1 │     1
   2 │     2
   3 │     3

julia> rename(df, :a => :d)
3×3 DataFrame
 Row │ d      b      c     
     │ Int64  Int64  Int64
─────┼─────────────────────
   1 │     1      4      7
   2 │     2      5      8
   3 │     3      6      9

julia> select(df, :a => identity => f)
3×1 DataFrame
 Row │ __a__ 
     │ Int64
─────┼───────
   1 │     1
   2 │     2
   3 │     3

julia> rename(df, :a => identity => f)
ERROR: MethodError: no method matching rename!(::DataFrame, ::Vector{Pair{Symbol, Pair{typeof(identity), typeof(f)}}})

julia> rename(df, :a => f)
ERROR: MethodError: no method matching rename!(::DataFrame, ::Vector{Pair{Symbol, typeof(f)}})
```

**Comment by nalimilan** [comment]
`rename(df, :cols => f)` makes sense to me as a syntax. I'm not sure how useful it is but it sounds in line with the other syntaxes we already support.

**Comment by bkamins** [comment]
I was thinking about it. What @nathanrboyer wants is `rename(df, ["a", "b"] => f)`, so multiple columns would be allowed on LHS (and possibly, I assume other selectors). We currently do not allow it. The only syntax we support is `:col1 => :col2` (i.e. single column to a single column).

Now, apart from a comprehension another way to express what @nathanrboyer wants is:
```
rename(n -> ifelse(n in ["a", "b"] ? f(n) : n), df)
```
or equivalently:
```
rename(df) do n
    ifelse(n in ["a", "b"] ? f(n) : n)
end
```

I know they are longer. But I am just asking myself if we add these examples to a manual, along with the comprehension `rename(df, [n => n * "_new" for n in ["a", "b"]])` maybe that would be enough.

This boils down to a question if the pattern `rename(df, ["a", "b"] => f)` is needed frequently enough to warrant adding it. Because it is a rare use-case, then I would tend to improve the documentation and skip adding this option.

@nalimilan - indeed `["a", "b"] => f` is supported in `select` etc., but it means something completely different, as it means:
1. take columns `:a` and `:b` from `df`.
2. pass them as positional arguments to `f`
3. store the result in the `:a_b_f` column

**Comment by nalimilan** [comment]
Right, `["a", "b"] .=> f` would be more appropriate (if we add it at all).

**Comment by bkamins** [comment]
> `["a", "b"] .=> f`

Yes, but this is exactly why I am hesitating to add it. Since user (@nathanrboyer as an example) might have a different intuition, and `["a", "b"] .=> f` is in my opinion by far not obvious (even if we added it).

Simply put `=>` here and `=>` in operation specification syntax have completely different meanings and I would not want to build a feeling for the users that they are the same.

**Comment by nathanrboyer** [comment]
Broadcasting when multiple columns are selected makes sense to me.

Although my intuition is that the `=>` in `rename` is the second one in `select`, which does work without the dot:
```julia
julia> select(df, [:a, :b] .=> identity => f)
3×2 DataFrame
 Row │ __a__  __B__
     │ Int64  Int64
─────┼──────────────
   1 │     1      4
   2 │     2      5
   3 │     3      6

julia> select(df, Not(:c) .=> identity => f)
3×2 DataFrame
 Row │ __a__  __B__
     │ Int64  Int64
─────┼──────────────
   1 │     1      4
   2 │     2      5
   3 │     3      6
```

I would want `rename(df, Not(:col) .=> f)` to work. Quick idea of a use case:
```julia
df = DataFrame(Time = 0.0:0.1:0.3, Temp1 = rand(4), Temp2 = rand(4), Temp3 = rand(4))
function longname(x)
    x = string(x)
    n = last(x)
    if chop(x) == "Temp"
        return "Temperature " * n * " (°F)"
    else
        throw(ArgumentError("unsupported input string"))
    end
end
rename(df, Not(:Time) .=> longname)
```

**Comment by adienes** [comment]
the syntax does kinda make sense to me but I think it should definitely have to be broadcasted (and maybe set a custom error message for when people inevitably attempt to chain a third `=>` in)

**Comment by jariji** [comment]
There is potential ambiguity between callable and `AbstractString`.

```jl
julia> struct StrFunc <: AbstractString
       s
       end

julia> ((;s)::StrFunc)(x) = string(s,x)

julia> StrFunc("hello ")("world")
"hello world"

julia> rename(df, :a => StrFunc("hello "))
```

**Comment by david-macmahon** [comment]
Not realizing that there already is a `rename` method that takes a function as its first argument, I suggested just that on Slack.  It turns out that method, `rename(f::Function, df::AbstractDataFrame)`, renames all columns but other methods following that same pattern could have an additional argument of a symbol to rename one column or a Vector of symbols to rename multiple columns:
```julia
rename(uppercase, df, :col)

rename(ab->uppercase.(ab), df, [:a, :b])

rename(df, [:a, :b]) do ab
    uppercase.(ab)
end
```

**Comment by bkamins** [comment]
I like the proposal of @david-macmahon (if it is OK with the other discutants). Then the signature would be:
```
rename(f::Function, df::AbstractDataFrame; cols=All())
```
so the example call would be:
```
rename(uppercase, df, Not(:col))
```

Note that I would make the last argument a keyword. There are two reasons for this:
1. Then it is clearer that this is a non-standard syntax and what the parameter means (at least I feel like this).
2. It is consistent with the `describe` method that follows this pattern e.g. you write `describe(df, cols=[:a, :b])` to describe only columns `:a` and `:b`.

What do you think?

**Comment by bkamins** [comment]
In #3380 I have added the `rename(f::Function, df::AbstractDataFrame; cols=All())` variant.

I have thought a lot about the other proposal, and I do not think we should add it. I think it is better to keep `rename` API simple. Otherwise we would open a list of discussions if things like:
```
rename(df, Not(:a, :b) .=> uppercase, Cols(startswith("something")) .=> lowercase)
```
should work and how would they work (such things work in `select` et al., but they are very complex and most likely would be never used in `rename`). I think it is better to limit the API of `rename`. At the same time the `rename(f::Function, df::AbstractDataFrame; cols=All())` variant gives a way to easily achieve what users would want in a typical case.
