### ISSUE TITLE
using propertynames on GroupedDataFrame

### ISSUE THREAD

**Issue by matthieugomez** [JuliaData/DataFrames.jl#3443]
The documentation discusses the fact that one can use either `names` and `propertynames`  to get the name of variables in DataFrame, where the first function returns a vector of strings and the second one returns a vector symbols. However, for a GroupedDataFrame, `propertynames` returns `(:parent, :cols, :groups, :idx, :starts, :ends, :ngroups, :keymap, :lazy_lock)`. I found this confusing and to solve this, I think it would be good to define

```julia
Base.propertynames(df::GroupedDataFrame) = propertynames(parent(df))
```

**Comment by bkamins** [comment]
I understand you have an issue about the inconsistency between `names` and `propertynames`.

The current design is based on the following reasoning:
* the `names` function does not promise anything, it only promises to return names of columns. Therefore it can be defined on `GroupedDataFrame`.
* the `propertynames` on the other hand has a promise. It promises that if you write `gdf.x` when `:x` was returned as a property of `gdf` object you get a meaningful result. The problem is that it is not clear what `gdf.x` should return if `gdf` is a `GroupedDataFrame` having a column `:x`. We cannot just return `parent(gdf).x` as it is not the same. For this reason currently `propertynames` and `getproperty` was left untouched from the default.

However, for the future we could discuss changing it provided that we find some meaningful value that would be returned by `gdf.x`.

**Comment by matthieugomez** [comment]
Maybe an alternative would be to have a better suggestion than `propertynames` to return the column names as symbol? Is `Symbol.(names())' supposed to work? If so, I would suggest to mention this in the doc instead of  `propertynames`

**Comment by bkamins** [comment]
you can use `propertynames(parent(gdf))`. I think this is the preferred pattern (as it falls back to `propertynames` and gives a right context that `gdf` is a view of its parent. I understand you would put this suggestion in `names` docstring?

**Comment by matthieugomez** [comment]
Right. That being said, it's a  really complicated thing to remember.
Could you suggest people to use something else than `propertynames' instead? For instance, would `Symbol.(names)' work? If not, how about `names(df, Symbol)`?

**Comment by bkamins** [comment]
> `propertynames` is a bit weird in the context of DataFrames

This is not a function introduced by DataFrames.jl. It is a Base function that returns names of properties of an object. And column names as symbols are names of properties of `DataFrame`.

---

In general the current design is to use strings as column names as people found it easier to work with. The use of `Symbol` is a bit of a legacy (indeed, it is a bit faster, but the difference is minimal).

We could add `Symbol.(names(df))` suggestion.

**Comment by matthieugomez** [comment]
Great — I think suggesting `Symbol.(names(df))` is the best option
