### ISSUE TITLE
Failure to measure string length properly for escape sequences

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaData/DataFrames.jl#526]
```
julia> df = DataFrame(A = 1:3, B = [-1, 0, +1], C = ["x", "y", "z\nz"])
3x3 DataFrame
|-------|---|----|-------|
| Row # | A | B  | C     |
| 1     | 1 | -1 | "x"   |
| 2     | 2 | 0  | "y"   |
| 3     | 3 | 1  | "z\nz" |
```

**Comment by quinnj** [comment]
It seems the current DataFrame show code actually `print`s out string columns, which makes the above example show like
```julia
ulia> df = DataFrame(A = 1:3, B = [-1, 0, +1], C = ["x", "y", "z\nz"])
3×3 DataFrames.DataFrame
│ Row │ A │ B  │ C  │
├─────┼───┼────┼────┤
│ 1   │ 1 │ -1 │ x  │
│ 2   │ 2 │ 0  │ y  │
│ 3   │ 3 │ 1  │ z
z │
```
which I'd say is arguably worse than before. I think for String types, we should print them "escaped" with double quotes before and just make sure we calculate the right size for things as this original issue brought up (i.e. making sure control characters have a "length" of 2 since they'll be printed with the escape character).

**Comment by cjprybol** [comment]
Dup of https://github.com/JuliaData/DataFrames.jl/issues/551, which has been addressed
