### ISSUE TITLE
HDF5 support

### ISSUE THREAD

**Issue by tshort** [JuliaData/DataFrames.jl#64]
This may be nice way to exchange data with R and pandas.

See Tim Holy's work based on code by Konrad Hinsen:

https://github.com/timholy/julia_hdf5

An on-disk Hdf5DataFrame might be nice, too.

**Comment by mmacedoeu** [comment]
Hey guys, i am brand new to Julia evaluating it for use on Big Data, and I have this scenario: storing and reading Time Series of data coming from sensors, the volume of data is so that cannot be loaded on memory. So I have two questions, is DataFrames capable of handling Big Data, and how can I save DataFrames using HDF5/JLD example ?

**Comment by damiendr** [comment]
I have some code to read HDF5 tables into Julia efficiently (using HDF5's built-in memory layout conversion), and I'm willing to contribute some code to turn that into a DataFrame. In which package should this go?

**Comment by damiendr** [comment]
To clarify -- The existing support for compound types in HDF5.jl is inefficient (type instability, redundant storage of field types and names with each row, and unnecessary data copying/conversion), making it unsuitable for large datasets. But I'm a bit wary of modifying HDF5.jl to return a DataFrame, because this would break existing code, and there may be some tricky cases with tables that contain arrays and strings (everything needs to be `isbits`). So maybe the best compromise would be a direct route into DataFrames.

**Comment by nalimilan** [comment]
I think HDF5-DataFrames interop code should live either in HDF5.jl or in a special package. If it lives in HDF5.jl, it doesn't necessarily mean that a `DataFrame` should be returned by default. I guess the best design would be to implement a DataStreams `Source`/`Sink`, which will allow loading the file into a `DataFrame`, but also streaming it to any kind of structure or file format, as well as doing operations with Query.jl.

**Comment by damiendr** [comment]
Thanks for the pointers. I've made a quick & dirty package here: https://github.com/damiendr/HDFTables.jl
It needs more testing, but it should work just fine for tables of scalars. I'll look into the Source/Sink interface and see how I can work with that.
