### ISSUE TITLE
Don't show entire 1M-column DataFrame by default

### ISSUE THREAD

**Issue by garborg** [JuliaData/DataFrames.jl#760]

**Comment by johnmyleswhite** [comment]
Is the number of rows a problem? Or a number of columns? I thought we only showed as many rows as would, in some sense, fit into the REPL window's height.

**Comment by garborg** [comment]
```julia
d = Dict{Symbol,Vector}()
for _ = 1:2_000_000
    d[symbol(randstring(8))] = [1]
end
df = DataFrame(d)
```
prints to the REPL for minutes.

**Comment by johnmyleswhite** [comment]
So it's the number of columns that matters, not the number of rows. We could follow dplyr's lead and only print the number of columns that fits in the screen horizontally. Alternatively, we could just cap things at a constant like 25.

**Comment by garborg** [comment]
Oh yes, columns -- your request for clarification went right over my head. Either of those option, or something like two screen widths, seem fine to me.

**Comment by johnmyleswhite** [comment]
Will try to look into this soon. We may need a heuristic for deciding whether we even calculate the screen width contribution of all columns since that could be slow on its own.

**Comment by garborg** [comment]
Makes sense.

**Comment by johnmyleswhite** [comment]
And thanks for closing the old issues. You must have the highest close rate of all DataFrames contributors by far now.

**Comment by garborg** [comment]
Thanks. I'm a bit surprised there are still 49 watchers.

**Comment by johnmyleswhite** [comment]
I suspect the watch count never decreases. (Except in response to this comment.)

**Comment by bkamins** [comment]
I get this problem very often when working with real data.

I would recommend adding an additional argument to `show` and `showrows` that could be called for example `maxchunks` that would limit the number of printed chunks with the following rules:

* `maxchunks` less than `1`: print all chunks
* `maxchunks` equal to `1`: print one chunk (this should be default so that we get only one screen)
* `maxchunks` greater than `1`: print given number of chunks

If number of printed chunks would be limited by this argument an information that not all columns of data frame were printed should be given.

**Comment by johnmyleswhite** [comment]
I suspect we should use the number of characters rather than a number of chunks since it's more immediately interpretable -- unless you already mean chunks to indicate number of characters.

**Comment by bkamins** [comment]
I was thinking of a parameter that would allow to limit `nchunks` in `showrows`
https://github.com/JuliaStats/DataFrames.jl/blob/master/src/abstractdataframe/show.jl#L344
as this would be a simple modification of existing code and currently single chunk is already sized to fit the screen.

It could be an additional parameter (to stay compatible with current definition of `show`) or `splitchunks` could be changed from `Bool` to some other type that would allow choosing from options: 1) do not split to chunks, 2) split to full number of chunks, 3) limit number of chunks to a given value (with default as one chunk).

**Comment by nalimilan** [comment]
I've been wondering for a while whether it wouldn't make more sense to print a summary of columns instead (one per line, with type information and a few elements). When you have more than 10 columns the current output is nearly useless.

**Comment by johnmyleswhite** [comment]
Please don't do that. If you have a large monitor, it's very useful to print all columns up to around 25 columns.

**Comment by johnmyleswhite** [comment]
It would involve an enormous increase in the amount of work, but Presto leads you scroll left and right and redisplays a subset of the table, which makes it possible to view much larger tables.

**Comment by nalimilan** [comment]
> Please don't do that. If you have a large monitor, it's very useful to print all columns up to around 25 columns.

The rule could be smarter: if all collumns don't fit on screen, switch to a synthetic summary of columns.

**Comment by johnmyleswhite** [comment]
In the end, I think you should decide what you think is best. From my perspective, I have literally never once in my life found it useful to see a summary of the columns printed out. The dplyr approach of printing a subset of columns (which I also don't like) is still better than that in my opinion. But it should be your call to make.

**Comment by bkamins** [comment]
Here is what I think.
Consider the following code:

```
x = DataFrame(rand(100, 100))
```
1. you already have a problem if you are in REPL and forgotten `;`.
2. if you want to see columns you can get them by writing `show(x, false)`. In this view adding a trailing column with first few values of each column could be considered.
3. what I would like to see is that `show(x)` behaves like `dplyr`, but if I write `show(x, n)` it shows 'n' pages of columns instead of one - the default; and `show(x, true)` could print all columns (the current default)

This could be implemented as something like:
```
Base.show(df::AbstractDataFrame) = Base.show(df::AbstractDataFrame, 1)
Base.show(df::AbstractDataFrame, n::Int) # this has to be implemented
Base.show(df::AbstractDataFrame, splitchunks::Bool) # remove default value of splitchunks
```
in `src/abstractdataframe/show.jl`.

**Comment by nalimilan** [comment]
I think the difficult point is that data frames can be used with relatively small data sets as well as with very large ones (especially in terms of numbers of columns). I'd tend to favor the latter, and I think I could go as far as printing just the `x×y DataFrame` summary line by default, which is the greatest common divisor of these uses cases. Disregarding this extreme solution, it seems we all agree that the default should be relatively short in any case, i.e. should never go beyond a screen page. That's probably the most important point.

@bkamins Sounds interesting, but do you think you would really need to be able to pass any number `n`? Aren't you likely to want only one page of columns, or all of them (i.e. a boolean rather than an integer)?

**Comment by bkamins** [comment]
The case for passing `n` is not very strong - simply sometimes when using `dplyr` I wish I could see two or three pages not one page of columns. I proposed it because making this change is relatively simple, but it is not something that is really crucial.

However, what I find important is the following. Most often I `show` DataFrame when I load it from disk or generate somehow and want to check if everything went OK. the bare minimum in such cases is to:

1. know number of columns and rows in the data set;
2. see first and last rows in the data set;
3. see several first and last column names in the data set and their types (and preferably also their contents).

Actually this is approximately what you get in Julia when you `show` arrays (like `eye(100)`) and I like it. However, in order to make it work for DataFrames the code of `showrows` would have to be changed more significantly (probably by selecting maximum `k` for which first `k` and last `k` or `k-1` columns would fit on the display). I did not propose it as it is a more complex rewrite of the code.

**Comment by nalimilan** [comment]
Your description also matches my use case, but for that a display with one column per row, with type and start/end elements, would also work.

Anyway, feel free to make a PR with whatever reasonable solution you think it not too hard to implement from the current state of the code.

**Comment by cjprybol** [comment]
Fixed by @bkamins in https://github.com/JuliaData/DataFrames.jl/pull/995
